:- module(movefact,[]).
have_type(pound,normal).
have_type(karate_chop,fighting).
have_type(double_slap,normal).
have_type(comet_punch,normal).
have_type(mega_punch,normal).
have_type(pay_day,normal).
have_type(fire_punch,fire).
have_type(ice_punch,ice).
have_type(thunder_punch,electric).
have_type(scratch,normal).
have_type(vice_grip,normal).
have_type(guillotine,normal).
have_type(razor_wind,normal).
have_type(swords_dance,normal).
have_type(cut,normal).
have_type(gust,flying).
have_type(wing_attack,flying).
have_type(whirlwind,normal).
have_type(fly,flying).
have_type(bind,normal).
have_type(slam,normal).
have_type(vine_whip,grass).
have_type(stomp,normal).
have_type(double_kick,fighting).
have_type(mega_kick,normal).
have_type(jump_kick,fighting).
have_type(rolling_kick,fighting).
have_type(sand_attack,ground).
have_type(headbutt,normal).
have_type(horn_attack,normal).
have_type(fury_attack,normal).
have_type(horn_drill,normal).
have_type(tackle,normal).
have_type(body_slam,normal).
have_type(wrap,normal).
have_type(take_down,normal).
have_type(thrash,normal).
have_type(double_edge,normal).
have_type(tail_whip,normal).
have_type(poison_sting,poison).
have_type(twineedle,bug).
have_type(pin_missile,bug).
have_type(leer,normal).
have_type(bite,dark).
have_type(growl,normal).
have_type(roar,normal).
have_type(sing,normal).
have_type(supersonic,normal).
have_type(sonic_boom,normal).
have_type(disable,normal).
have_type(acid,poison).
have_type(ember,fire).
have_type(flamethrower,fire).
have_type(mist,ice).
have_type(water_gun,water).
have_type(hydro_pump,water).
have_type(surf,water).
have_type(ice_beam,ice).
have_type(blizzard,ice).
have_type(psybeam,psychic).
have_type(bubble_beam,water).
have_type(aurora_beam,ice).
have_type(hyper_beam,normal).
have_type(peck,flying).
have_type(drill_peck,flying).
have_type(submission,fighting).
have_type(low_kick,fighting).
have_type(counter,fighting).
have_type(seismic_toss,fighting).
have_type(strength,normal).
have_type(absorb,grass).
have_type(mega_drain,grass).
have_type(leech_seed,grass).
have_type(growth,normal).
have_type(razor_leaf,grass).
have_type(solar_beam,grass).
have_type(poison_powder,poison).
have_type(stun_spore,grass).
have_type(sleep_powder,grass).
have_type(petal_dance,grass).
have_type(string_shot,bug).
have_type(dragon_rage,dragon).
have_type(fire_spin,fire).
have_type(thunder_shock,electric).
have_type(thunderbolt,electric).
have_type(thunder_wave,electric).
have_type(thunder,electric).
have_type(rock_throw,rock).
have_type(earthquake,ground).
have_type(fissure,ground).
have_type(dig,ground).
have_type(toxic,poison).
have_type(confusion,psychic).
have_type(psychic,psychic).
have_type(hypnosis,psychic).
have_type(meditate,psychic).
have_type(agility,psychic).
have_type(quick_attack,normal).
have_type(rage,normal).
have_type(teleport,psychic).
have_type(night_shade,ghost).
have_type(mimic,normal).
have_type(screech,normal).
have_type(double_team,normal).
have_type(recover,normal).
have_type(harden,normal).
have_type(minimize,normal).
have_type(smokescreen,normal).
have_type(confuse_ray,ghost).
have_type(withdraw,water).
have_type(defense_curl,normal).
have_type(barrier,psychic).
have_type(light_screen,psychic).
have_type(haze,ice).
have_type(reflect,psychic).
have_type(focus_energy,normal).
have_type(bide,normal).
have_type(metronome,normal).
have_type(mirror_move,flying).
have_type(self_destruct,normal).
have_type(egg_bomb,normal).
have_type(lick,ghost).
have_type(smog,poison).
have_type(sludge,poison).
have_type(bone_club,ground).
have_type(fire_blast,fire).
have_type(waterfall,water).
have_type(clamp,water).
have_type(swift,normal).
have_type(skull_bash,normal).
have_type(spike_cannon,normal).
have_type(constrict,normal).
have_type(amnesia,psychic).
have_type(kinesis,psychic).
have_type(soft_boiled,normal).
have_type(high_jump_kick,fighting).
have_type(glare,normal).
have_type(dream_eater,psychic).
have_type(poison_gas,poison).
have_type(barrage,normal).
have_type(leech_life,bug).
have_type(lovely_kiss,normal).
have_type(sky_attack,flying).
have_type(transform,normal).
have_type(bubble,water).
have_type(dizzy_punch,normal).
have_type(spore,grass).
have_type(flash,normal).
have_type(psywave,psychic).
have_type(splash,normal).
have_type(acid_armor,poison).
have_type(crabhammer,water).
have_type(explosion,normal).
have_type(fury_swipes,normal).
have_type(bonemerang,ground).
have_type(rest,psychic).
have_type(rock_slide,rock).
have_type(hyper_fang,normal).
have_type(sharpen,normal).
have_type(conversion,normal).
have_type(tri_attack,normal).
have_type(super_fang,normal).
have_type(slash,normal).
have_type(substitute,normal).
have_type(struggle,normal).
have_type(sketch,normal).
have_type(triple_kick,fighting).
have_type(thief,dark).
have_type(spider_web,bug).
have_type(mind_reader,normal).
have_type(nightmare,ghost).
have_type(flame_wheel,fire).
have_type(snore,normal).
have_type(curse,ghost).
have_type(flail,normal).
have_type(conversion_2,normal).
have_type(aeroblast,flying).
have_type(cotton_spore,grass).
have_type(reversal,fighting).
have_type(spite,ghost).
have_type(powder_snow,ice).
have_type(protect,normal).
have_type(mach_punch,fighting).
have_type(scary_face,normal).
have_type(feint_attack,dark).
have_type(sweet_kiss,fairy).
have_type(belly_drum,normal).
have_type(sludge_bomb,poison).
have_type(mud_slap,ground).
have_type(octazooka,water).
have_type(spikes,ground).
have_type(zap_cannon,electric).
have_type(foresight,normal).
have_type(destiny_bond,ghost).
have_type(perish_song,normal).
have_type(icy_wind,ice).
have_type(detect,fighting).
have_type(bone_rush,ground).
have_type(lock_on,normal).
have_type(outrage,dragon).
have_type(sandstorm,rock).
have_type(giga_drain,grass).
have_type(endure,normal).
have_type(charm,fairy).
have_type(rollout,rock).
have_type(false_swipe,normal).
have_type(swagger,normal).
have_type(milk_drink,normal).
have_type(spark,electric).
have_type(fury_cutter,bug).
have_type(steel_wing,steel).
have_type(mean_look,normal).
have_type(attract,normal).
have_type(sleep_talk,normal).
have_type(heal_bell,normal).
have_type(return,normal).
have_type(present,normal).
have_type(frustration,normal).
have_type(safeguard,normal).
have_type(pain_split,normal).
have_type(sacred_fire,fire).
have_type(magnitude,ground).
have_type(dynamic_punch,fighting).
have_type(megahorn,bug).
have_type(dragon_breath,dragon).
have_type(baton_pass,normal).
have_type(encore,normal).
have_type(pursuit,dark).
have_type(rapid_spin,normal).
have_type(sweet_scent,normal).
have_type(iron_tail,steel).
have_type(metal_claw,steel).
have_type(vital_throw,fighting).
have_type(morning_sun,normal).
have_type(synthesis,grass).
have_type(moonlight,fairy).
have_type(hidden_power,normal).
have_type(cross_chop,fighting).
have_type(twister,dragon).
have_type(rain_dance,water).
have_type(sunny_day,fire).
have_type(crunch,dark).
have_type(mirror_coat,psychic).
have_type(psych_up,normal).
have_type(extreme_speed,normal).
have_type(ancient_power,rock).
have_type(shadow_ball,ghost).
have_type(future_sight,psychic).
have_type(rock_smash,fighting).
have_type(whirlpool,water).
have_type(beat_up,dark).
have_type(fake_out,normal).
have_type(uproar,normal).
have_type(stockpile,normal).
have_type(spit_up,normal).
have_type(swallow,normal).
have_type(heat_wave,fire).
have_type(hail,ice).
have_type(torment,dark).
have_type(flatter,dark).
have_type(will_o_wisp,fire).
have_type(memento,dark).
have_type(facade,normal).
have_type(focus_punch,fighting).
have_type(smelling_salts,normal).
have_type(follow_me,normal).
have_type(nature_power,normal).
have_type(charge,electric).
have_type(taunt,dark).
have_type(helping_hand,normal).
have_type(trick,psychic).
have_type(role_play,psychic).
have_type(wish,normal).
have_type(assist,normal).
have_type(ingrain,grass).
have_type(superpower,fighting).
have_type(magic_coat,psychic).
have_type(recycle,normal).
have_type(revenge,fighting).
have_type(brick_break,fighting).
have_type(yawn,normal).
have_type(knock_off,dark).
have_type(endeavor,normal).
have_type(eruption,fire).
have_type(skill_swap,psychic).
have_type(imprison,psychic).
have_type(refresh,normal).
have_type(grudge,ghost).
have_type(snatch,dark).
have_type(secret_power,normal).
have_type(dive,water).
have_type(arm_thrust,fighting).
have_type(camouflage,normal).
have_type(tail_glow,bug).
have_type(luster_purge,psychic).
have_type(mist_ball,psychic).
have_type(feather_dance,flying).
have_type(teeter_dance,normal).
have_type(blaze_kick,fire).
have_type(mud_sport,ground).
have_type(ice_ball,ice).
have_type(needle_arm,grass).
have_type(slack_off,normal).
have_type(hyper_voice,normal).
have_type(poison_fang,poison).
have_type(crush_claw,normal).
have_type(blast_burn,fire).
have_type(hydro_cannon,water).
have_type(meteor_mash,steel).
have_type(astonish,ghost).
have_type(weather_ball,normal).
have_type(aromatherapy,grass).
have_type(fake_tears,dark).
have_type(air_cutter,flying).
have_type(overheat,fire).
have_type(odor_sleuth,normal).
have_type(rock_tomb,rock).
have_type(silver_wind,bug).
have_type(metal_sound,steel).
have_type(grass_whistle,grass).
have_type(tickle,normal).
have_type(cosmic_power,psychic).
have_type(water_spout,water).
have_type(signal_beam,bug).
have_type(shadow_punch,ghost).
have_type(extrasensory,psychic).
have_type(sky_uppercut,fighting).
have_type(sand_tomb,ground).
have_type(sheer_cold,ice).
have_type(muddy_water,water).
have_type(bullet_seed,grass).
have_type(aerial_ace,flying).
have_type(icicle_spear,ice).
have_type(iron_defense,steel).
have_type(block,normal).
have_type(howl,normal).
have_type(dragon_claw,dragon).
have_type(frenzy_plant,grass).
have_type(bulk_up,fighting).
have_type(bounce,flying).
have_type(mud_shot,ground).
have_type(poison_tail,poison).
have_type(covet,normal).
have_type(volt_tackle,electric).
have_type(magical_leaf,grass).
have_type(water_sport,water).
have_type(calm_mind,psychic).
have_type(leaf_blade,grass).
have_type(dragon_dance,dragon).
have_type(rock_blast,rock).
have_type(shock_wave,electric).
have_type(water_pulse,water).
have_type(doom_desire,steel).
have_type(psycho_boost,psychic).
have_type(roost,flying).
have_type(gravity,psychic).
have_type(miracle_eye,psychic).
have_type(wake_up_slap,fighting).
have_type(hammer_arm,fighting).
have_type(gyro_ball,steel).
have_type(healing_wish,psychic).
have_type(brine,water).
have_type(natural_gift,normal).
have_type(feint,normal).
have_type(pluck,flying).
have_type(tailwind,flying).
have_type(acupressure,normal).
have_type(metal_burst,steel).
have_type(u_turn,bug).
have_type(close_combat,fighting).
have_type(payback,dark).
have_type(assurance,dark).
have_type(embargo,dark).
have_type(fling,dark).
have_type(psycho_shift,psychic).
have_type(trump_card,normal).
have_type(heal_block,psychic).
have_type(wring_out,normal).
have_type(power_trick,psychic).
have_type(gastro_acid,poison).
have_type(lucky_chant,normal).
have_type(me_first,normal).
have_type(copycat,normal).
have_type(power_swap,psychic).
have_type(guard_swap,psychic).
have_type(punishment,dark).
have_type(last_resort,normal).
have_type(worry_seed,grass).
have_type(sucker_punch,dark).
have_type(toxic_spikes,poison).
have_type(heart_swap,psychic).
have_type(aqua_ring,water).
have_type(magnet_rise,electric).
have_type(flare_blitz,fire).
have_type(force_palm,fighting).
have_type(aura_sphere,fighting).
have_type(rock_polish,rock).
have_type(poison_jab,poison).
have_type(dark_pulse,dark).
have_type(night_slash,dark).
have_type(aqua_tail,water).
have_type(seed_bomb,grass).
have_type(air_slash,flying).
have_type(x_scissor,bug).
have_type(bug_buzz,bug).
have_type(dragon_pulse,dragon).
have_type(dragon_rush,dragon).
have_type(power_gem,rock).
have_type(drain_punch,fighting).
have_type(vacuum_wave,fighting).
have_type(focus_blast,fighting).
have_type(energy_ball,grass).
have_type(brave_bird,flying).
have_type(earth_power,ground).
have_type(switcheroo,dark).
have_type(giga_impact,normal).
have_type(nasty_plot,dark).
have_type(bullet_punch,steel).
have_type(avalanche,ice).
have_type(ice_shard,ice).
have_type(shadow_claw,ghost).
have_type(thunder_fang,electric).
have_type(ice_fang,ice).
have_type(fire_fang,fire).
have_type(shadow_sneak,ghost).
have_type(mud_bomb,ground).
have_type(psycho_cut,psychic).
have_type(zen_headbutt,psychic).
have_type(mirror_shot,steel).
have_type(flash_cannon,steel).
have_type(rock_climb,normal).
have_type(defog,flying).
have_type(trick_room,psychic).
have_type(draco_meteor,dragon).
have_type(discharge,electric).
have_type(lava_plume,fire).
have_type(leaf_storm,grass).
have_type(power_whip,grass).
have_type(rock_wrecker,rock).
have_type(cross_poison,poison).
have_type(gunk_shot,poison).
have_type(iron_head,steel).
have_type(magnet_bomb,steel).
have_type(stone_edge,rock).
have_type(captivate,normal).
have_type(stealth_rock,rock).
have_type(grass_knot,grass).
have_type(chatter,flying).
have_type(judgment,normal).
have_type(bug_bite,bug).
have_type(charge_beam,electric).
have_type(wood_hammer,grass).
have_type(aqua_jet,water).
have_type(attack_order,bug).
have_type(defend_order,bug).
have_type(heal_order,bug).
have_type(head_smash,rock).
have_type(double_hit,normal).
have_type(roar_of_time,dragon).
have_type(spacial_rend,dragon).
have_type(lunar_dance,psychic).
have_type(crush_grip,normal).
have_type(magma_storm,fire).
have_type(dark_void,dark).
have_type(seed_flare,grass).
have_type(ominous_wind,ghost).
have_type(shadow_force,ghost).
have_type(hone_claws,dark).
have_type(wide_guard,rock).
have_type(guard_split,psychic).
have_type(power_split,psychic).
have_type(wonder_room,psychic).
have_type(psyshock,psychic).
have_type(venoshock,poison).
have_type(autotomize,steel).
have_type(rage_powder,bug).
have_type(telekinesis,psychic).
have_type(magic_room,psychic).
have_type(smack_down,rock).
have_type(storm_throw,fighting).
have_type(flame_burst,fire).
have_type(sludge_wave,poison).
have_type(quiver_dance,bug).
have_type(heavy_slam,steel).
have_type(synchronoise,psychic).
have_type(electro_ball,electric).
have_type(soak,water).
have_type(flame_charge,fire).
have_type(coil,poison).
have_type(low_sweep,fighting).
have_type(acid_spray,poison).
have_type(foul_play,dark).
have_type(simple_beam,normal).
have_type(entrainment,normal).
have_type(after_you,normal).
have_type(round,normal).
have_type(echoed_voice,normal).
have_type(chip_away,normal).
have_type(clear_smog,poison).
have_type(stored_power,psychic).
have_type(quick_guard,fighting).
have_type(ally_switch,psychic).
have_type(scald,water).
have_type(shell_smash,normal).
have_type(heal_pulse,psychic).
have_type(hex,ghost).
have_type(sky_drop,flying).
have_type(shift_gear,steel).
have_type(circle_throw,fighting).
have_type(incinerate,fire).
have_type(quash,dark).
have_type(acrobatics,flying).
have_type(reflect_type,normal).
have_type(retaliate,normal).
have_type(final_gambit,fighting).
have_type(bestow,normal).
have_type(inferno,fire).
have_type(water_pledge,water).
have_type(fire_pledge,fire).
have_type(grass_pledge,grass).
have_type(volt_switch,electric).
have_type(struggle_bug,bug).
have_type(bulldoze,ground).
have_type(frost_breath,ice).
have_type(dragon_tail,dragon).
have_type(work_up,normal).
have_type(electroweb,electric).
have_type(wild_charge,electric).
have_type(drill_run,ground).
have_type(dual_chop,dragon).
have_type(heart_stamp,psychic).
have_type(horn_leech,grass).
have_type(sacred_sword,fighting).
have_type(razor_shell,water).
have_type(heat_crash,fire).
have_type(leaf_tornado,grass).
have_type(steamroller,bug).
have_type(cotton_guard,grass).
have_type(night_daze,dark).
have_type(psystrike,psychic).
have_type(tail_slap,normal).
have_type(hurricane,flying).
have_type(head_charge,normal).
have_type(gear_grind,steel).
have_type(searing_shot,fire).
have_type(techno_blast,normal).
have_type(relic_song,normal).
have_type(secret_sword,fighting).
have_type(glaciate,ice).
have_type(bolt_strike,electric).
have_type(blue_flare,fire).
have_type(fiery_dance,fire).
have_type(freeze_shock,ice).
have_type(ice_burn,ice).
have_type(snarl,dark).
have_type(icicle_crash,ice).
have_type(v_create,fire).
have_type(fusion_flare,fire).
have_type(fusion_bolt,electric).
have_type(flying_press,fighting).
have_type(mat_block,fighting).
have_type(belch,poison).
have_type(rototiller,ground).
have_type(sticky_web,bug).
have_type(fell_stinger,bug).
have_type(phantom_force,ghost).
have_type(trick_or_treat,ghost).
have_type(noble_roar,normal).
have_type(ion_deluge,electric).
have_type(parabolic_charge,electric).
have_type(forests_curse,grass).
have_type(petal_blizzard,grass).
have_type(freeze_dry,ice).
have_type(disarming_voice,fairy).
have_type(parting_shot,dark).
have_type(topsy_turvy,dark).
have_type(draining_kiss,fairy).
have_type(crafty_shield,fairy).
have_type(flower_shield,fairy).
have_type(grassy_terrain,grass).
have_type(misty_terrain,fairy).
have_type(electrify,electric).
have_type(play_rough,fairy).
have_type(fairy_wind,fairy).
have_type(moonblast,fairy).
have_type(boomburst,normal).
have_type(fairy_lock,fairy).
have_type(kings_shield,steel).
have_type(play_nice,normal).
have_type(confide,normal).
have_type(diamond_storm,rock).
have_type(steam_eruption,water).
have_type(hyperspace_hole,psychic).
have_type(water_shuriken,water).
have_type(mystical_fire,fire).
have_type(spiky_shield,grass).
have_type(aromatic_mist,fairy).
have_type(eerie_impulse,electric).
have_type(venom_drench,poison).
have_type(powder,bug).
have_type(geomancy,fairy).
have_type(magnetic_flux,electric).
have_type(happy_hour,normal).
have_type(electric_terrain,electric).
have_type(dazzling_gleam,fairy).
have_type(celebrate,normal).
have_type(hold_hands,normal).
have_type(baby_doll_eyes,fairy).
have_type(nuzzle,electric).
have_type(hold_back,normal).
have_type(infestation,bug).
have_type(power_up_punch,fighting).
have_type(oblivion_wing,flying).
have_type(thousand_arrows,ground).
have_type(thousand_waves,ground).
have_type(lands_wrath,ground).
have_type(light_of_ruin,fairy).
have_type(origin_pulse,water).
have_type(precipice_blades,ground).
have_type(dragon_ascent,flying).
have_type(hyperspace_fury,dark).
have_type(shadow_rush,shadow).
have_type(shadow_blast,shadow).
have_type(shadow_blitz,shadow).
have_type(shadow_bolt,shadow).
have_type(shadow_break,shadow).
have_type(shadow_chill,shadow).
have_type(shadow_end,shadow).
have_type(shadow_fire,shadow).
have_type(shadow_rave,shadow).
have_type(shadow_storm,shadow).
have_type(shadow_wave,shadow).
have_type(shadow_down,shadow).
have_type(shadow_half,shadow).
have_type(shadow_hold,shadow).
have_type(shadow_mist,shadow).
have_type(shadow_panic,shadow).
have_type(shadow_shed,shadow).
have_type(shadow_sky,shadow).
move(pound).
move(karate_chop).
move(double_slap).
move(comet_punch).
move(mega_punch).
move(pay_day).
move(fire_punch).
move(ice_punch).
move(thunder_punch).
move(scratch).
move(vice_grip).
move(guillotine).
move(razor_wind).
move(swords_dance).
move(cut).
move(gust).
move(wing_attack).
move(whirlwind).
move(fly).
move(bind).
move(slam).
move(vine_whip).
move(stomp).
move(double_kick).
move(mega_kick).
move(jump_kick).
move(rolling_kick).
move(sand_attack).
move(headbutt).
move(horn_attack).
move(fury_attack).
move(horn_drill).
move(tackle).
move(body_slam).
move(wrap).
move(take_down).
move(thrash).
move(double_edge).
move(tail_whip).
move(poison_sting).
move(twineedle).
move(pin_missile).
move(leer).
move(bite).
move(growl).
move(roar).
move(sing).
move(supersonic).
move(sonic_boom).
move(disable).
move(acid).
move(ember).
move(flamethrower).
move(mist).
move(water_gun).
move(hydro_pump).
move(surf).
move(ice_beam).
move(blizzard).
move(psybeam).
move(bubble_beam).
move(aurora_beam).
move(hyper_beam).
move(peck).
move(drill_peck).
move(submission).
move(low_kick).
move(counter).
move(seismic_toss).
move(strength).
move(absorb).
move(mega_drain).
move(leech_seed).
move(growth).
move(razor_leaf).
move(solar_beam).
move(poison_powder).
move(stun_spore).
move(sleep_powder).
move(petal_dance).
move(string_shot).
move(dragon_rage).
move(fire_spin).
move(thunder_shock).
move(thunderbolt).
move(thunder_wave).
move(thunder).
move(rock_throw).
move(earthquake).
move(fissure).
move(dig).
move(toxic).
move(confusion).
move(psychic).
move(hypnosis).
move(meditate).
move(agility).
move(quick_attack).
move(rage).
move(teleport).
move(night_shade).
move(mimic).
move(screech).
move(double_team).
move(recover).
move(harden).
move(minimize).
move(smokescreen).
move(confuse_ray).
move(withdraw).
move(defense_curl).
move(barrier).
move(light_screen).
move(haze).
move(reflect).
move(focus_energy).
move(bide).
move(metronome).
move(mirror_move).
move(self_destruct).
move(egg_bomb).
move(lick).
move(smog).
move(sludge).
move(bone_club).
move(fire_blast).
move(waterfall).
move(clamp).
move(swift).
move(skull_bash).
move(spike_cannon).
move(constrict).
move(amnesia).
move(kinesis).
move(soft_boiled).
move(high_jump_kick).
move(glare).
move(dream_eater).
move(poison_gas).
move(barrage).
move(leech_life).
move(lovely_kiss).
move(sky_attack).
move(transform).
move(bubble).
move(dizzy_punch).
move(spore).
move(flash).
move(psywave).
move(splash).
move(acid_armor).
move(crabhammer).
move(explosion).
move(fury_swipes).
move(bonemerang).
move(rest).
move(rock_slide).
move(hyper_fang).
move(sharpen).
move(conversion).
move(tri_attack).
move(super_fang).
move(slash).
move(substitute).
move(struggle).
move(sketch).
move(triple_kick).
move(thief).
move(spider_web).
move(mind_reader).
move(nightmare).
move(flame_wheel).
move(snore).
move(curse).
move(flail).
move(conversion_2).
move(aeroblast).
move(cotton_spore).
move(reversal).
move(spite).
move(powder_snow).
move(protect).
move(mach_punch).
move(scary_face).
move(feint_attack).
move(sweet_kiss).
move(belly_drum).
move(sludge_bomb).
move(mud_slap).
move(octazooka).
move(spikes).
move(zap_cannon).
move(foresight).
move(destiny_bond).
move(perish_song).
move(icy_wind).
move(detect).
move(bone_rush).
move(lock_on).
move(outrage).
move(sandstorm).
move(giga_drain).
move(endure).
move(charm).
move(rollout).
move(false_swipe).
move(swagger).
move(milk_drink).
move(spark).
move(fury_cutter).
move(steel_wing).
move(mean_look).
move(attract).
move(sleep_talk).
move(heal_bell).
move(return).
move(present).
move(frustration).
move(safeguard).
move(pain_split).
move(sacred_fire).
move(magnitude).
move(dynamic_punch).
move(megahorn).
move(dragon_breath).
move(baton_pass).
move(encore).
move(pursuit).
move(rapid_spin).
move(sweet_scent).
move(iron_tail).
move(metal_claw).
move(vital_throw).
move(morning_sun).
move(synthesis).
move(moonlight).
move(hidden_power).
move(cross_chop).
move(twister).
move(rain_dance).
move(sunny_day).
move(crunch).
move(mirror_coat).
move(psych_up).
move(extreme_speed).
move(ancient_power).
move(shadow_ball).
move(future_sight).
move(rock_smash).
move(whirlpool).
move(beat_up).
move(fake_out).
move(uproar).
move(stockpile).
move(spit_up).
move(swallow).
move(heat_wave).
move(hail).
move(torment).
move(flatter).
move(will_o_wisp).
move(memento).
move(facade).
move(focus_punch).
move(smelling_salts).
move(follow_me).
move(nature_power).
move(charge).
move(taunt).
move(helping_hand).
move(trick).
move(role_play).
move(wish).
move(assist).
move(ingrain).
move(superpower).
move(magic_coat).
move(recycle).
move(revenge).
move(brick_break).
move(yawn).
move(knock_off).
move(endeavor).
move(eruption).
move(skill_swap).
move(imprison).
move(refresh).
move(grudge).
move(snatch).
move(secret_power).
move(dive).
move(arm_thrust).
move(camouflage).
move(tail_glow).
move(luster_purge).
move(mist_ball).
move(feather_dance).
move(teeter_dance).
move(blaze_kick).
move(mud_sport).
move(ice_ball).
move(needle_arm).
move(slack_off).
move(hyper_voice).
move(poison_fang).
move(crush_claw).
move(blast_burn).
move(hydro_cannon).
move(meteor_mash).
move(astonish).
move(weather_ball).
move(aromatherapy).
move(fake_tears).
move(air_cutter).
move(overheat).
move(odor_sleuth).
move(rock_tomb).
move(silver_wind).
move(metal_sound).
move(grass_whistle).
move(tickle).
move(cosmic_power).
move(water_spout).
move(signal_beam).
move(shadow_punch).
move(extrasensory).
move(sky_uppercut).
move(sand_tomb).
move(sheer_cold).
move(muddy_water).
move(bullet_seed).
move(aerial_ace).
move(icicle_spear).
move(iron_defense).
move(block).
move(howl).
move(dragon_claw).
move(frenzy_plant).
move(bulk_up).
move(bounce).
move(mud_shot).
move(poison_tail).
move(covet).
move(volt_tackle).
move(magical_leaf).
move(water_sport).
move(calm_mind).
move(leaf_blade).
move(dragon_dance).
move(rock_blast).
move(shock_wave).
move(water_pulse).
move(doom_desire).
move(psycho_boost).
move(roost).
move(gravity).
move(miracle_eye).
move(wake_up_slap).
move(hammer_arm).
move(gyro_ball).
move(healing_wish).
move(brine).
move(natural_gift).
move(feint).
move(pluck).
move(tailwind).
move(acupressure).
move(metal_burst).
move(u_turn).
move(close_combat).
move(payback).
move(assurance).
move(embargo).
move(fling).
move(psycho_shift).
move(trump_card).
move(heal_block).
move(wring_out).
move(power_trick).
move(gastro_acid).
move(lucky_chant).
move(me_first).
move(copycat).
move(power_swap).
move(guard_swap).
move(punishment).
move(last_resort).
move(worry_seed).
move(sucker_punch).
move(toxic_spikes).
move(heart_swap).
move(aqua_ring).
move(magnet_rise).
move(flare_blitz).
move(force_palm).
move(aura_sphere).
move(rock_polish).
move(poison_jab).
move(dark_pulse).
move(night_slash).
move(aqua_tail).
move(seed_bomb).
move(air_slash).
move(x_scissor).
move(bug_buzz).
move(dragon_pulse).
move(dragon_rush).
move(power_gem).
move(drain_punch).
move(vacuum_wave).
move(focus_blast).
move(energy_ball).
move(brave_bird).
move(earth_power).
move(switcheroo).
move(giga_impact).
move(nasty_plot).
move(bullet_punch).
move(avalanche).
move(ice_shard).
move(shadow_claw).
move(thunder_fang).
move(ice_fang).
move(fire_fang).
move(shadow_sneak).
move(mud_bomb).
move(psycho_cut).
move(zen_headbutt).
move(mirror_shot).
move(flash_cannon).
move(rock_climb).
move(defog).
move(trick_room).
move(draco_meteor).
move(discharge).
move(lava_plume).
move(leaf_storm).
move(power_whip).
move(rock_wrecker).
move(cross_poison).
move(gunk_shot).
move(iron_head).
move(magnet_bomb).
move(stone_edge).
move(captivate).
move(stealth_rock).
move(grass_knot).
move(chatter).
move(judgment).
move(bug_bite).
move(charge_beam).
move(wood_hammer).
move(aqua_jet).
move(attack_order).
move(defend_order).
move(heal_order).
move(head_smash).
move(double_hit).
move(roar_of_time).
move(spacial_rend).
move(lunar_dance).
move(crush_grip).
move(magma_storm).
move(dark_void).
move(seed_flare).
move(ominous_wind).
move(shadow_force).
move(hone_claws).
move(wide_guard).
move(guard_split).
move(power_split).
move(wonder_room).
move(psyshock).
move(venoshock).
move(autotomize).
move(rage_powder).
move(telekinesis).
move(magic_room).
move(smack_down).
move(storm_throw).
move(flame_burst).
move(sludge_wave).
move(quiver_dance).
move(heavy_slam).
move(synchronoise).
move(electro_ball).
move(soak).
move(flame_charge).
move(coil).
move(low_sweep).
move(acid_spray).
move(foul_play).
move(simple_beam).
move(entrainment).
move(after_you).
move(round).
move(echoed_voice).
move(chip_away).
move(clear_smog).
move(stored_power).
move(quick_guard).
move(ally_switch).
move(scald).
move(shell_smash).
move(heal_pulse).
move(hex).
move(sky_drop).
move(shift_gear).
move(circle_throw).
move(incinerate).
move(quash).
move(acrobatics).
move(reflect_type).
move(retaliate).
move(final_gambit).
move(bestow).
move(inferno).
move(water_pledge).
move(fire_pledge).
move(grass_pledge).
move(volt_switch).
move(struggle_bug).
move(bulldoze).
move(frost_breath).
move(dragon_tail).
move(work_up).
move(electroweb).
move(wild_charge).
move(drill_run).
move(dual_chop).
move(heart_stamp).
move(horn_leech).
move(sacred_sword).
move(razor_shell).
move(heat_crash).
move(leaf_tornado).
move(steamroller).
move(cotton_guard).
move(night_daze).
move(psystrike).
move(tail_slap).
move(hurricane).
move(head_charge).
move(gear_grind).
move(searing_shot).
move(techno_blast).
move(relic_song).
move(secret_sword).
move(glaciate).
move(bolt_strike).
move(blue_flare).
move(fiery_dance).
move(freeze_shock).
move(ice_burn).
move(snarl).
move(icicle_crash).
move(v_create).
move(fusion_flare).
move(fusion_bolt).
move(flying_press).
move(mat_block).
move(belch).
move(rototiller).
move(sticky_web).
move(fell_stinger).
move(phantom_force).
move(trick_or_treat).
move(noble_roar).
move(ion_deluge).
move(parabolic_charge).
move(forests_curse).
move(petal_blizzard).
move(freeze_dry).
move(disarming_voice).
move(parting_shot).
move(topsy_turvy).
move(draining_kiss).
move(crafty_shield).
move(flower_shield).
move(grassy_terrain).
move(misty_terrain).
move(electrify).
move(play_rough).
move(fairy_wind).
move(moonblast).
move(boomburst).
move(fairy_lock).
move(kings_shield).
move(play_nice).
move(confide).
move(diamond_storm).
move(steam_eruption).
move(hyperspace_hole).
move(water_shuriken).
move(mystical_fire).
move(spiky_shield).
move(aromatic_mist).
move(eerie_impulse).
move(venom_drench).
move(powder).
move(geomancy).
move(magnetic_flux).
move(happy_hour).
move(electric_terrain).
move(dazzling_gleam).
move(celebrate).
move(hold_hands).
move(baby_doll_eyes).
move(nuzzle).
move(hold_back).
move(infestation).
move(power_up_punch).
move(oblivion_wing).
move(thousand_arrows).
move(thousand_waves).
move(lands_wrath).
move(light_of_ruin).
move(origin_pulse).
move(precipice_blades).
move(dragon_ascent).
move(hyperspace_fury).
move(shadow_rush).
move(shadow_blast).
move(shadow_blitz).
move(shadow_bolt).
move(shadow_break).
move(shadow_chill).
move(shadow_end).
move(shadow_fire).
move(shadow_rave).
move(shadow_storm).
move(shadow_wave).
move(shadow_down).
move(shadow_half).
move(shadow_hold).
move(shadow_mist).
move(shadow_panic).
move(shadow_shed).
move(shadow_sky).
