:- module(movefact,[]).
have_type(pound,normal).
have_type(karate-chop,fighting).
have_type(double-slap,normal).
have_type(comet-punch,normal).
have_type(mega-punch,normal).
have_type(pay-day,normal).
have_type(fire-punch,fire).
have_type(ice-punch,ice).
have_type(thunder-punch,electric).
have_type(scratch,normal).
have_type(vice-grip,normal).
have_type(guillotine,normal).
have_type(razor-wind,normal).
have_type(swords-dance,normal).
have_type(cut,normal).
have_type(gust,flying).
have_type(wing-attack,flying).
have_type(whirlwind,normal).
have_type(fly,flying).
have_type(bind,normal).
have_type(slam,normal).
have_type(vine-whip,grass).
have_type(stomp,normal).
have_type(double-kick,fighting).
have_type(mega-kick,normal).
have_type(jump-kick,fighting).
have_type(rolling-kick,fighting).
have_type(sand-attack,ground).
have_type(headbutt,normal).
have_type(horn-attack,normal).
have_type(fury-attack,normal).
have_type(horn-drill,normal).
have_type(tackle,normal).
have_type(body-slam,normal).
have_type(wrap,normal).
have_type(take-down,normal).
have_type(thrash,normal).
have_type(double-edge,normal).
have_type(tail-whip,normal).
have_type(poison-sting,poison).
have_type(twineedle,bug).
have_type(pin-missile,bug).
have_type(leer,normal).
have_type(bite,dark).
have_type(growl,normal).
have_type(roar,normal).
have_type(sing,normal).
have_type(supersonic,normal).
have_type(sonic-boom,normal).
have_type(disable,normal).
have_type(acid,poison).
have_type(ember,fire).
have_type(flamethrower,fire).
have_type(mist,ice).
have_type(water-gun,water).
have_type(hydro-pump,water).
have_type(surf,water).
have_type(ice-beam,ice).
have_type(blizzard,ice).
have_type(psybeam,psychic).
have_type(bubble-beam,water).
have_type(aurora-beam,ice).
have_type(hyper-beam,normal).
have_type(peck,flying).
have_type(drill-peck,flying).
have_type(submission,fighting).
have_type(low-kick,fighting).
have_type(counter,fighting).
have_type(seismic-toss,fighting).
have_type(strength,normal).
have_type(absorb,grass).
have_type(mega-drain,grass).
have_type(leech-seed,grass).
have_type(growth,normal).
have_type(razor-leaf,grass).
have_type(solar-beam,grass).
have_type(poison-powder,poison).
have_type(stun-spore,grass).
have_type(sleep-powder,grass).
have_type(petal-dance,grass).
have_type(string-shot,bug).
have_type(dragon-rage,dragon).
have_type(fire-spin,fire).
have_type(thunder-shock,electric).
have_type(thunderbolt,electric).
have_type(thunder-wave,electric).
have_type(thunder,electric).
have_type(rock-throw,rock).
have_type(earthquake,ground).
have_type(fissure,ground).
have_type(dig,ground).
have_type(toxic,poison).
have_type(confusion,psychic).
have_type(psychic,psychic).
have_type(hypnosis,psychic).
have_type(meditate,psychic).
have_type(agility,psychic).
have_type(quick-attack,normal).
have_type(rage,normal).
have_type(teleport,psychic).
have_type(night-shade,ghost).
have_type(mimic,normal).
have_type(screech,normal).
have_type(double-team,normal).
have_type(recover,normal).
have_type(harden,normal).
have_type(minimize,normal).
have_type(smokescreen,normal).
have_type(confuse-ray,ghost).
have_type(withdraw,water).
have_type(defense-curl,normal).
have_type(barrier,psychic).
have_type(light-screen,psychic).
have_type(haze,ice).
have_type(reflect,psychic).
have_type(focus-energy,normal).
have_type(bide,normal).
have_type(metronome,normal).
have_type(mirror-move,flying).
have_type(self-destruct,normal).
have_type(egg-bomb,normal).
have_type(lick,ghost).
have_type(smog,poison).
have_type(sludge,poison).
have_type(bone-club,ground).
have_type(fire-blast,fire).
have_type(waterfall,water).
have_type(clamp,water).
have_type(swift,normal).
have_type(skull-bash,normal).
have_type(spike-cannon,normal).
have_type(constrict,normal).
have_type(amnesia,psychic).
have_type(kinesis,psychic).
have_type(soft-boiled,normal).
have_type(high-jump-kick,fighting).
have_type(glare,normal).
have_type(dream-eater,psychic).
have_type(poison-gas,poison).
have_type(barrage,normal).
have_type(leech-life,bug).
have_type(lovely-kiss,normal).
have_type(sky-attack,flying).
have_type(transform,normal).
have_type(bubble,water).
have_type(dizzy-punch,normal).
have_type(spore,grass).
have_type(flash,normal).
have_type(psywave,psychic).
have_type(splash,normal).
have_type(acid-armor,poison).
have_type(crabhammer,water).
have_type(explosion,normal).
have_type(fury-swipes,normal).
have_type(bonemerang,ground).
have_type(rest,psychic).
have_type(rock-slide,rock).
have_type(hyper-fang,normal).
have_type(sharpen,normal).
have_type(conversion,normal).
have_type(tri-attack,normal).
have_type(super-fang,normal).
have_type(slash,normal).
have_type(substitute,normal).
have_type(struggle,normal).
have_type(sketch,normal).
have_type(triple-kick,fighting).
have_type(thief,dark).
have_type(spider-web,bug).
have_type(mind-reader,normal).
have_type(nightmare,ghost).
have_type(flame-wheel,fire).
have_type(snore,normal).
have_type(curse,ghost).
have_type(flail,normal).
have_type(conversion-2,normal).
have_type(aeroblast,flying).
have_type(cotton-spore,grass).
have_type(reversal,fighting).
have_type(spite,ghost).
have_type(powder-snow,ice).
have_type(protect,normal).
have_type(mach-punch,fighting).
have_type(scary-face,normal).
have_type(feint-attack,dark).
have_type(sweet-kiss,fairy).
have_type(belly-drum,normal).
have_type(sludge-bomb,poison).
have_type(mud-slap,ground).
have_type(octazooka,water).
have_type(spikes,ground).
have_type(zap-cannon,electric).
have_type(foresight,normal).
have_type(destiny-bond,ghost).
have_type(perish-song,normal).
have_type(icy-wind,ice).
have_type(detect,fighting).
have_type(bone-rush,ground).
have_type(lock-on,normal).
have_type(outrage,dragon).
have_type(sandstorm,rock).
have_type(giga-drain,grass).
have_type(endure,normal).
have_type(charm,fairy).
have_type(rollout,rock).
have_type(false-swipe,normal).
have_type(swagger,normal).
have_type(milk-drink,normal).
have_type(spark,electric).
have_type(fury-cutter,bug).
have_type(steel-wing,steel).
have_type(mean-look,normal).
have_type(attract,normal).
have_type(sleep-talk,normal).
have_type(heal-bell,normal).
have_type(return,normal).
have_type(present,normal).
have_type(frustration,normal).
have_type(safeguard,normal).
have_type(pain-split,normal).
have_type(sacred-fire,fire).
have_type(magnitude,ground).
have_type(dynamic-punch,fighting).
have_type(megahorn,bug).
have_type(dragon-breath,dragon).
have_type(baton-pass,normal).
have_type(encore,normal).
have_type(pursuit,dark).
have_type(rapid-spin,normal).
have_type(sweet-scent,normal).
have_type(iron-tail,steel).
have_type(metal-claw,steel).
have_type(vital-throw,fighting).
have_type(morning-sun,normal).
have_type(synthesis,grass).
have_type(moonlight,fairy).
have_type(hidden-power,normal).
have_type(cross-chop,fighting).
have_type(twister,dragon).
have_type(rain-dance,water).
have_type(sunny-day,fire).
have_type(crunch,dark).
have_type(mirror-coat,psychic).
have_type(psych-up,normal).
have_type(extreme-speed,normal).
have_type(ancient-power,rock).
have_type(shadow-ball,ghost).
have_type(future-sight,psychic).
have_type(rock-smash,fighting).
have_type(whirlpool,water).
have_type(beat-up,dark).
have_type(fake-out,normal).
have_type(uproar,normal).
have_type(stockpile,normal).
have_type(spit-up,normal).
have_type(swallow,normal).
have_type(heat-wave,fire).
have_type(hail,ice).
have_type(torment,dark).
have_type(flatter,dark).
have_type(will-o-wisp,fire).
have_type(memento,dark).
have_type(facade,normal).
have_type(focus-punch,fighting).
have_type(smelling-salts,normal).
have_type(follow-me,normal).
have_type(nature-power,normal).
have_type(charge,electric).
have_type(taunt,dark).
have_type(helping-hand,normal).
have_type(trick,psychic).
have_type(role-play,psychic).
have_type(wish,normal).
have_type(assist,normal).
have_type(ingrain,grass).
have_type(superpower,fighting).
have_type(magic-coat,psychic).
have_type(recycle,normal).
have_type(revenge,fighting).
have_type(brick-break,fighting).
have_type(yawn,normal).
have_type(knock-off,dark).
have_type(endeavor,normal).
have_type(eruption,fire).
have_type(skill-swap,psychic).
have_type(imprison,psychic).
have_type(refresh,normal).
have_type(grudge,ghost).
have_type(snatch,dark).
have_type(secret-power,normal).
have_type(dive,water).
have_type(arm-thrust,fighting).
have_type(camouflage,normal).
have_type(tail-glow,bug).
have_type(luster-purge,psychic).
have_type(mist-ball,psychic).
have_type(feather-dance,flying).
have_type(teeter-dance,normal).
have_type(blaze-kick,fire).
have_type(mud-sport,ground).
have_type(ice-ball,ice).
have_type(needle-arm,grass).
have_type(slack-off,normal).
have_type(hyper-voice,normal).
have_type(poison-fang,poison).
have_type(crush-claw,normal).
have_type(blast-burn,fire).
have_type(hydro-cannon,water).
have_type(meteor-mash,steel).
have_type(astonish,ghost).
have_type(weather-ball,normal).
have_type(aromatherapy,grass).
have_type(fake-tears,dark).
have_type(air-cutter,flying).
have_type(overheat,fire).
have_type(odor-sleuth,normal).
have_type(rock-tomb,rock).
have_type(silver-wind,bug).
have_type(metal-sound,steel).
have_type(grass-whistle,grass).
have_type(tickle,normal).
have_type(cosmic-power,psychic).
have_type(water-spout,water).
have_type(signal-beam,bug).
have_type(shadow-punch,ghost).
have_type(extrasensory,psychic).
have_type(sky-uppercut,fighting).
have_type(sand-tomb,ground).
have_type(sheer-cold,ice).
have_type(muddy-water,water).
have_type(bullet-seed,grass).
have_type(aerial-ace,flying).
have_type(icicle-spear,ice).
have_type(iron-defense,steel).
have_type(block,normal).
have_type(howl,normal).
have_type(dragon-claw,dragon).
have_type(frenzy-plant,grass).
have_type(bulk-up,fighting).
have_type(bounce,flying).
have_type(mud-shot,ground).
have_type(poison-tail,poison).
have_type(covet,normal).
have_type(volt-tackle,electric).
have_type(magical-leaf,grass).
have_type(water-sport,water).
have_type(calm-mind,psychic).
have_type(leaf-blade,grass).
have_type(dragon-dance,dragon).
have_type(rock-blast,rock).
have_type(shock-wave,electric).
have_type(water-pulse,water).
have_type(doom-desire,steel).
have_type(psycho-boost,psychic).
have_type(roost,flying).
have_type(gravity,psychic).
have_type(miracle-eye,psychic).
have_type(wake-up-slap,fighting).
have_type(hammer-arm,fighting).
have_type(gyro-ball,steel).
have_type(healing-wish,psychic).
have_type(brine,water).
have_type(natural-gift,normal).
have_type(feint,normal).
have_type(pluck,flying).
have_type(tailwind,flying).
have_type(acupressure,normal).
have_type(metal-burst,steel).
have_type(u-turn,bug).
have_type(close-combat,fighting).
have_type(payback,dark).
have_type(assurance,dark).
have_type(embargo,dark).
have_type(fling,dark).
have_type(psycho-shift,psychic).
have_type(trump-card,normal).
have_type(heal-block,psychic).
have_type(wring-out,normal).
have_type(power-trick,psychic).
have_type(gastro-acid,poison).
have_type(lucky-chant,normal).
have_type(me-first,normal).
have_type(copycat,normal).
have_type(power-swap,psychic).
have_type(guard-swap,psychic).
have_type(punishment,dark).
have_type(last-resort,normal).
have_type(worry-seed,grass).
have_type(sucker-punch,dark).
have_type(toxic-spikes,poison).
have_type(heart-swap,psychic).
have_type(aqua-ring,water).
have_type(magnet-rise,electric).
have_type(flare-blitz,fire).
have_type(force-palm,fighting).
have_type(aura-sphere,fighting).
have_type(rock-polish,rock).
have_type(poison-jab,poison).
have_type(dark-pulse,dark).
have_type(night-slash,dark).
have_type(aqua-tail,water).
have_type(seed-bomb,grass).
have_type(air-slash,flying).
have_type(x-scissor,bug).
have_type(bug-buzz,bug).
have_type(dragon-pulse,dragon).
have_type(dragon-rush,dragon).
have_type(power-gem,rock).
have_type(drain-punch,fighting).
have_type(vacuum-wave,fighting).
have_type(focus-blast,fighting).
have_type(energy-ball,grass).
have_type(brave-bird,flying).
have_type(earth-power,ground).
have_type(switcheroo,dark).
have_type(giga-impact,normal).
have_type(nasty-plot,dark).
have_type(bullet-punch,steel).
have_type(avalanche,ice).
have_type(ice-shard,ice).
have_type(shadow-claw,ghost).
have_type(thunder-fang,electric).
have_type(ice-fang,ice).
have_type(fire-fang,fire).
have_type(shadow-sneak,ghost).
have_type(mud-bomb,ground).
have_type(psycho-cut,psychic).
have_type(zen-headbutt,psychic).
have_type(mirror-shot,steel).
have_type(flash-cannon,steel).
have_type(rock-climb,normal).
have_type(defog,flying).
have_type(trick-room,psychic).
have_type(draco-meteor,dragon).
have_type(discharge,electric).
have_type(lava-plume,fire).
have_type(leaf-storm,grass).
have_type(power-whip,grass).
have_type(rock-wrecker,rock).
have_type(cross-poison,poison).
have_type(gunk-shot,poison).
have_type(iron-head,steel).
have_type(magnet-bomb,steel).
have_type(stone-edge,rock).
have_type(captivate,normal).
have_type(stealth-rock,rock).
have_type(grass-knot,grass).
have_type(chatter,flying).
have_type(judgment,normal).
have_type(bug-bite,bug).
have_type(charge-beam,electric).
have_type(wood-hammer,grass).
have_type(aqua-jet,water).
have_type(attack-order,bug).
have_type(defend-order,bug).
have_type(heal-order,bug).
have_type(head-smash,rock).
have_type(double-hit,normal).
have_type(roar-of-time,dragon).
have_type(spacial-rend,dragon).
have_type(lunar-dance,psychic).
have_type(crush-grip,normal).
have_type(magma-storm,fire).
have_type(dark-void,dark).
have_type(seed-flare,grass).
have_type(ominous-wind,ghost).
have_type(shadow-force,ghost).
have_type(hone-claws,dark).
have_type(wide-guard,rock).
have_type(guard-split,psychic).
have_type(power-split,psychic).
have_type(wonder-room,psychic).
have_type(psyshock,psychic).
have_type(venoshock,poison).
have_type(autotomize,steel).
have_type(rage-powder,bug).
have_type(telekinesis,psychic).
have_type(magic-room,psychic).
have_type(smack-down,rock).
have_type(storm-throw,fighting).
have_type(flame-burst,fire).
have_type(sludge-wave,poison).
have_type(quiver-dance,bug).
have_type(heavy-slam,steel).
have_type(synchronoise,psychic).
have_type(electro-ball,electric).
have_type(soak,water).
have_type(flame-charge,fire).
have_type(coil,poison).
have_type(low-sweep,fighting).
have_type(acid-spray,poison).
have_type(foul-play,dark).
have_type(simple-beam,normal).
have_type(entrainment,normal).
have_type(after-you,normal).
have_type(round,normal).
have_type(echoed-voice,normal).
have_type(chip-away,normal).
have_type(clear-smog,poison).
have_type(stored-power,psychic).
have_type(quick-guard,fighting).
have_type(ally-switch,psychic).
have_type(scald,water).
have_type(shell-smash,normal).
have_type(heal-pulse,psychic).
have_type(hex,ghost).
have_type(sky-drop,flying).
have_type(shift-gear,steel).
have_type(circle-throw,fighting).
have_type(incinerate,fire).
have_type(quash,dark).
have_type(acrobatics,flying).
have_type(reflect-type,normal).
have_type(retaliate,normal).
have_type(final-gambit,fighting).
have_type(bestow,normal).
have_type(inferno,fire).
have_type(water-pledge,water).
have_type(fire-pledge,fire).
have_type(grass-pledge,grass).
have_type(volt-switch,electric).
have_type(struggle-bug,bug).
have_type(bulldoze,ground).
have_type(frost-breath,ice).
have_type(dragon-tail,dragon).
have_type(work-up,normal).
have_type(electroweb,electric).
have_type(wild-charge,electric).
have_type(drill-run,ground).
have_type(dual-chop,dragon).
have_type(heart-stamp,psychic).
have_type(horn-leech,grass).
have_type(sacred-sword,fighting).
have_type(razor-shell,water).
have_type(heat-crash,fire).
have_type(leaf-tornado,grass).
have_type(steamroller,bug).
have_type(cotton-guard,grass).
have_type(night-daze,dark).
have_type(psystrike,psychic).
have_type(tail-slap,normal).
have_type(hurricane,flying).
have_type(head-charge,normal).
have_type(gear-grind,steel).
have_type(searing-shot,fire).
have_type(techno-blast,normal).
have_type(relic-song,normal).
have_type(secret-sword,fighting).
have_type(glaciate,ice).
have_type(bolt-strike,electric).
have_type(blue-flare,fire).
have_type(fiery-dance,fire).
have_type(freeze-shock,ice).
have_type(ice-burn,ice).
have_type(snarl,dark).
have_type(icicle-crash,ice).
have_type(v-create,fire).
have_type(fusion-flare,fire).
have_type(fusion-bolt,electric).
have_type(flying-press,fighting).
have_type(mat-block,fighting).
have_type(belch,poison).
have_type(rototiller,ground).
have_type(sticky-web,bug).
have_type(fell-stinger,bug).
have_type(phantom-force,ghost).
have_type(trick-or-treat,ghost).
have_type(noble-roar,normal).
have_type(ion-deluge,electric).
have_type(parabolic-charge,electric).
have_type(forests-curse,grass).
have_type(petal-blizzard,grass).
have_type(freeze-dry,ice).
have_type(disarming-voice,fairy).
have_type(parting-shot,dark).
have_type(topsy-turvy,dark).
have_type(draining-kiss,fairy).
have_type(crafty-shield,fairy).
have_type(flower-shield,fairy).
have_type(grassy-terrain,grass).
have_type(misty-terrain,fairy).
have_type(electrify,electric).
have_type(play-rough,fairy).
have_type(fairy-wind,fairy).
have_type(moonblast,fairy).
have_type(boomburst,normal).
have_type(fairy-lock,fairy).
have_type(kings-shield,steel).
have_type(play-nice,normal).
have_type(confide,normal).
have_type(diamond-storm,rock).
have_type(steam-eruption,water).
have_type(hyperspace-hole,psychic).
have_type(water-shuriken,water).
have_type(mystical-fire,fire).
have_type(spiky-shield,grass).
have_type(aromatic-mist,fairy).
have_type(eerie-impulse,electric).
have_type(venom-drench,poison).
have_type(powder,bug).
have_type(geomancy,fairy).
have_type(magnetic-flux,electric).
have_type(happy-hour,normal).
have_type(electric-terrain,electric).
have_type(dazzling-gleam,fairy).
have_type(celebrate,normal).
have_type(hold-hands,normal).
have_type(baby-doll-eyes,fairy).
have_type(nuzzle,electric).
have_type(hold-back,normal).
have_type(infestation,bug).
have_type(power-up-punch,fighting).
have_type(oblivion-wing,flying).
have_type(thousand-arrows,ground).
have_type(thousand-waves,ground).
have_type(lands-wrath,ground).
have_type(light-of-ruin,fairy).
have_type(origin-pulse,water).
have_type(precipice-blades,ground).
have_type(dragon-ascent,flying).
have_type(hyperspace-fury,dark).
have_type(shadow-rush,shadow).
have_type(shadow-blast,shadow).
have_type(shadow-blitz,shadow).
have_type(shadow-bolt,shadow).
have_type(shadow-break,shadow).
have_type(shadow-chill,shadow).
have_type(shadow-end,shadow).
have_type(shadow-fire,shadow).
have_type(shadow-rave,shadow).
have_type(shadow-storm,shadow).
have_type(shadow-wave,shadow).
have_type(shadow-down,shadow).
have_type(shadow-half,shadow).
have_type(shadow-hold,shadow).
have_type(shadow-mist,shadow).
have_type(shadow-panic,shadow).
have_type(shadow-shed,shadow).
have_type(shadow-sky,shadow).
move(pound).
move(karate-chop).
move(double-slap).
move(comet-punch).
move(mega-punch).
move(pay-day).
move(fire-punch).
move(ice-punch).
move(thunder-punch).
move(scratch).
move(vice-grip).
move(guillotine).
move(razor-wind).
move(swords-dance).
move(cut).
move(gust).
move(wing-attack).
move(whirlwind).
move(fly).
move(bind).
move(slam).
move(vine-whip).
move(stomp).
move(double-kick).
move(mega-kick).
move(jump-kick).
move(rolling-kick).
move(sand-attack).
move(headbutt).
move(horn-attack).
move(fury-attack).
move(horn-drill).
move(tackle).
move(body-slam).
move(wrap).
move(take-down).
move(thrash).
move(double-edge).
move(tail-whip).
move(poison-sting).
move(twineedle).
move(pin-missile).
move(leer).
move(bite).
move(growl).
move(roar).
move(sing).
move(supersonic).
move(sonic-boom).
move(disable).
move(acid).
move(ember).
move(flamethrower).
move(mist).
move(water-gun).
move(hydro-pump).
move(surf).
move(ice-beam).
move(blizzard).
move(psybeam).
move(bubble-beam).
move(aurora-beam).
move(hyper-beam).
move(peck).
move(drill-peck).
move(submission).
move(low-kick).
move(counter).
move(seismic-toss).
move(strength).
move(absorb).
move(mega-drain).
move(leech-seed).
move(growth).
move(razor-leaf).
move(solar-beam).
move(poison-powder).
move(stun-spore).
move(sleep-powder).
move(petal-dance).
move(string-shot).
move(dragon-rage).
move(fire-spin).
move(thunder-shock).
move(thunderbolt).
move(thunder-wave).
move(thunder).
move(rock-throw).
move(earthquake).
move(fissure).
move(dig).
move(toxic).
move(confusion).
move(psychic).
move(hypnosis).
move(meditate).
move(agility).
move(quick-attack).
move(rage).
move(teleport).
move(night-shade).
move(mimic).
move(screech).
move(double-team).
move(recover).
move(harden).
move(minimize).
move(smokescreen).
move(confuse-ray).
move(withdraw).
move(defense-curl).
move(barrier).
move(light-screen).
move(haze).
move(reflect).
move(focus-energy).
move(bide).
move(metronome).
move(mirror-move).
move(self-destruct).
move(egg-bomb).
move(lick).
move(smog).
move(sludge).
move(bone-club).
move(fire-blast).
move(waterfall).
move(clamp).
move(swift).
move(skull-bash).
move(spike-cannon).
move(constrict).
move(amnesia).
move(kinesis).
move(soft-boiled).
move(high-jump-kick).
move(glare).
move(dream-eater).
move(poison-gas).
move(barrage).
move(leech-life).
move(lovely-kiss).
move(sky-attack).
move(transform).
move(bubble).
move(dizzy-punch).
move(spore).
move(flash).
move(psywave).
move(splash).
move(acid-armor).
move(crabhammer).
move(explosion).
move(fury-swipes).
move(bonemerang).
move(rest).
move(rock-slide).
move(hyper-fang).
move(sharpen).
move(conversion).
move(tri-attack).
move(super-fang).
move(slash).
move(substitute).
move(struggle).
move(sketch).
move(triple-kick).
move(thief).
move(spider-web).
move(mind-reader).
move(nightmare).
move(flame-wheel).
move(snore).
move(curse).
move(flail).
move(conversion-2).
move(aeroblast).
move(cotton-spore).
move(reversal).
move(spite).
move(powder-snow).
move(protect).
move(mach-punch).
move(scary-face).
move(feint-attack).
move(sweet-kiss).
move(belly-drum).
move(sludge-bomb).
move(mud-slap).
move(octazooka).
move(spikes).
move(zap-cannon).
move(foresight).
move(destiny-bond).
move(perish-song).
move(icy-wind).
move(detect).
move(bone-rush).
move(lock-on).
move(outrage).
move(sandstorm).
move(giga-drain).
move(endure).
move(charm).
move(rollout).
move(false-swipe).
move(swagger).
move(milk-drink).
move(spark).
move(fury-cutter).
move(steel-wing).
move(mean-look).
move(attract).
move(sleep-talk).
move(heal-bell).
move(return).
move(present).
move(frustration).
move(safeguard).
move(pain-split).
move(sacred-fire).
move(magnitude).
move(dynamic-punch).
move(megahorn).
move(dragon-breath).
move(baton-pass).
move(encore).
move(pursuit).
move(rapid-spin).
move(sweet-scent).
move(iron-tail).
move(metal-claw).
move(vital-throw).
move(morning-sun).
move(synthesis).
move(moonlight).
move(hidden-power).
move(cross-chop).
move(twister).
move(rain-dance).
move(sunny-day).
move(crunch).
move(mirror-coat).
move(psych-up).
move(extreme-speed).
move(ancient-power).
move(shadow-ball).
move(future-sight).
move(rock-smash).
move(whirlpool).
move(beat-up).
move(fake-out).
move(uproar).
move(stockpile).
move(spit-up).
move(swallow).
move(heat-wave).
move(hail).
move(torment).
move(flatter).
move(will-o-wisp).
move(memento).
move(facade).
move(focus-punch).
move(smelling-salts).
move(follow-me).
move(nature-power).
move(charge).
move(taunt).
move(helping-hand).
move(trick).
move(role-play).
move(wish).
move(assist).
move(ingrain).
move(superpower).
move(magic-coat).
move(recycle).
move(revenge).
move(brick-break).
move(yawn).
move(knock-off).
move(endeavor).
move(eruption).
move(skill-swap).
move(imprison).
move(refresh).
move(grudge).
move(snatch).
move(secret-power).
move(dive).
move(arm-thrust).
move(camouflage).
move(tail-glow).
move(luster-purge).
move(mist-ball).
move(feather-dance).
move(teeter-dance).
move(blaze-kick).
move(mud-sport).
move(ice-ball).
move(needle-arm).
move(slack-off).
move(hyper-voice).
move(poison-fang).
move(crush-claw).
move(blast-burn).
move(hydro-cannon).
move(meteor-mash).
move(astonish).
move(weather-ball).
move(aromatherapy).
move(fake-tears).
move(air-cutter).
move(overheat).
move(odor-sleuth).
move(rock-tomb).
move(silver-wind).
move(metal-sound).
move(grass-whistle).
move(tickle).
move(cosmic-power).
move(water-spout).
move(signal-beam).
move(shadow-punch).
move(extrasensory).
move(sky-uppercut).
move(sand-tomb).
move(sheer-cold).
move(muddy-water).
move(bullet-seed).
move(aerial-ace).
move(icicle-spear).
move(iron-defense).
move(block).
move(howl).
move(dragon-claw).
move(frenzy-plant).
move(bulk-up).
move(bounce).
move(mud-shot).
move(poison-tail).
move(covet).
move(volt-tackle).
move(magical-leaf).
move(water-sport).
move(calm-mind).
move(leaf-blade).
move(dragon-dance).
move(rock-blast).
move(shock-wave).
move(water-pulse).
move(doom-desire).
move(psycho-boost).
move(roost).
move(gravity).
move(miracle-eye).
move(wake-up-slap).
move(hammer-arm).
move(gyro-ball).
move(healing-wish).
move(brine).
move(natural-gift).
move(feint).
move(pluck).
move(tailwind).
move(acupressure).
move(metal-burst).
move(u-turn).
move(close-combat).
move(payback).
move(assurance).
move(embargo).
move(fling).
move(psycho-shift).
move(trump-card).
move(heal-block).
move(wring-out).
move(power-trick).
move(gastro-acid).
move(lucky-chant).
move(me-first).
move(copycat).
move(power-swap).
move(guard-swap).
move(punishment).
move(last-resort).
move(worry-seed).
move(sucker-punch).
move(toxic-spikes).
move(heart-swap).
move(aqua-ring).
move(magnet-rise).
move(flare-blitz).
move(force-palm).
move(aura-sphere).
move(rock-polish).
move(poison-jab).
move(dark-pulse).
move(night-slash).
move(aqua-tail).
move(seed-bomb).
move(air-slash).
move(x-scissor).
move(bug-buzz).
move(dragon-pulse).
move(dragon-rush).
move(power-gem).
move(drain-punch).
move(vacuum-wave).
move(focus-blast).
move(energy-ball).
move(brave-bird).
move(earth-power).
move(switcheroo).
move(giga-impact).
move(nasty-plot).
move(bullet-punch).
move(avalanche).
move(ice-shard).
move(shadow-claw).
move(thunder-fang).
move(ice-fang).
move(fire-fang).
move(shadow-sneak).
move(mud-bomb).
move(psycho-cut).
move(zen-headbutt).
move(mirror-shot).
move(flash-cannon).
move(rock-climb).
move(defog).
move(trick-room).
move(draco-meteor).
move(discharge).
move(lava-plume).
move(leaf-storm).
move(power-whip).
move(rock-wrecker).
move(cross-poison).
move(gunk-shot).
move(iron-head).
move(magnet-bomb).
move(stone-edge).
move(captivate).
move(stealth-rock).
move(grass-knot).
move(chatter).
move(judgment).
move(bug-bite).
move(charge-beam).
move(wood-hammer).
move(aqua-jet).
move(attack-order).
move(defend-order).
move(heal-order).
move(head-smash).
move(double-hit).
move(roar-of-time).
move(spacial-rend).
move(lunar-dance).
move(crush-grip).
move(magma-storm).
move(dark-void).
move(seed-flare).
move(ominous-wind).
move(shadow-force).
move(hone-claws).
move(wide-guard).
move(guard-split).
move(power-split).
move(wonder-room).
move(psyshock).
move(venoshock).
move(autotomize).
move(rage-powder).
move(telekinesis).
move(magic-room).
move(smack-down).
move(storm-throw).
move(flame-burst).
move(sludge-wave).
move(quiver-dance).
move(heavy-slam).
move(synchronoise).
move(electro-ball).
move(soak).
move(flame-charge).
move(coil).
move(low-sweep).
move(acid-spray).
move(foul-play).
move(simple-beam).
move(entrainment).
move(after-you).
move(round).
move(echoed-voice).
move(chip-away).
move(clear-smog).
move(stored-power).
move(quick-guard).
move(ally-switch).
move(scald).
move(shell-smash).
move(heal-pulse).
move(hex).
move(sky-drop).
move(shift-gear).
move(circle-throw).
move(incinerate).
move(quash).
move(acrobatics).
move(reflect-type).
move(retaliate).
move(final-gambit).
move(bestow).
move(inferno).
move(water-pledge).
move(fire-pledge).
move(grass-pledge).
move(volt-switch).
move(struggle-bug).
move(bulldoze).
move(frost-breath).
move(dragon-tail).
move(work-up).
move(electroweb).
move(wild-charge).
move(drill-run).
move(dual-chop).
move(heart-stamp).
move(horn-leech).
move(sacred-sword).
move(razor-shell).
move(heat-crash).
move(leaf-tornado).
move(steamroller).
move(cotton-guard).
move(night-daze).
move(psystrike).
move(tail-slap).
move(hurricane).
move(head-charge).
move(gear-grind).
move(searing-shot).
move(techno-blast).
move(relic-song).
move(secret-sword).
move(glaciate).
move(bolt-strike).
move(blue-flare).
move(fiery-dance).
move(freeze-shock).
move(ice-burn).
move(snarl).
move(icicle-crash).
move(v-create).
move(fusion-flare).
move(fusion-bolt).
move(flying-press).
move(mat-block).
move(belch).
move(rototiller).
move(sticky-web).
move(fell-stinger).
move(phantom-force).
move(trick-or-treat).
move(noble-roar).
move(ion-deluge).
move(parabolic-charge).
move(forests-curse).
move(petal-blizzard).
move(freeze-dry).
move(disarming-voice).
move(parting-shot).
move(topsy-turvy).
move(draining-kiss).
move(crafty-shield).
move(flower-shield).
move(grassy-terrain).
move(misty-terrain).
move(electrify).
move(play-rough).
move(fairy-wind).
move(moonblast).
move(boomburst).
move(fairy-lock).
move(kings-shield).
move(play-nice).
move(confide).
move(diamond-storm).
move(steam-eruption).
move(hyperspace-hole).
move(water-shuriken).
move(mystical-fire).
move(spiky-shield).
move(aromatic-mist).
move(eerie-impulse).
move(venom-drench).
move(powder).
move(geomancy).
move(magnetic-flux).
move(happy-hour).
move(electric-terrain).
move(dazzling-gleam).
move(celebrate).
move(hold-hands).
move(baby-doll-eyes).
move(nuzzle).
move(hold-back).
move(infestation).
move(power-up-punch).
move(oblivion-wing).
move(thousand-arrows).
move(thousand-waves).
move(lands-wrath).
move(light-of-ruin).
move(origin-pulse).
move(precipice-blades).
move(dragon-ascent).
move(hyperspace-fury).
move(shadow-rush).
move(shadow-blast).
move(shadow-blitz).
move(shadow-bolt).
move(shadow-break).
move(shadow-chill).
move(shadow-end).
move(shadow-fire).
move(shadow-rave).
move(shadow-storm).
move(shadow-wave).
move(shadow-down).
move(shadow-half).
move(shadow-hold).
move(shadow-mist).
move(shadow-panic).
move(shadow-shed).
move(shadow-sky).
