:- module(powerfact,[]).
power(egg_bomb,100).
power(lick,20).
power(smog,20).
power(sludge,65).
power(bone_club,65).
power(fire_blast,120).
power(waterfall,80).
power(clamp,35).
power(swift,60).
power(skull_bash,100).
power(spike_cannon,20).
power(constrict,10).
power(amnesia,0).
power(kinesis,0).
power(softboiled,0).
power(hi_jump_kick,130).
power(glare,0).
power(dream_eater,100).
power(poison_gas,0).
power(barrage,15).
power(leech_life,20).
power(lovely_kiss,0).
power(sky_attack,140).
power(transform,0).
power(bubble,20).
power(dizzy_punch,70).
power(spore,0).
power(flash,0).
power(psywave,1).
power(splash,0).
power(acid_armor,0).
power(crabhammer,90).
power(explosion,250).
power(fury_swipes,18).
power(bonemerang,50).
power(rest,0).
power(rock_slide,75).
power(hyper_fang,80).
power(sharpen,0).
power(conversion,0).
power(tri_attack,80).
power(super_fang,1).
power(slash,70).
power(substitute,0).
power(struggle,50).
power(sketch,0).
power(triple_kick,10).
power(thief,40).
power(spider_web,0).
power(mind_reader,0).
power(nightmare,0).
power(flame_wheel,60).
power(snore,40).
power(curse,0).
power(flail,1).
power(conversion_2,0).
power(aeroblast,100).
power(cotton_spore,0).
power(reversal,1).
power(spite,0).
power(powder_snow,40).
power(protect,0).
power(mach_punch,40).
power(scary_face,0).
power(faint_attack,60).
power(sweet_kiss,0).
power(belly_drum,0).
power(sludge_bomb,90).
power(mud_slap,20).
power(octazooka,65).
power(spikes,0).
power(zap_cannon,120).
power(foresight,0).
power(destiny_bond,0).
power(perish_song,0).
power(icy_wind,55).
power(detect,0).
power(bone_rush,25).
power(lock_on,0).
power(outrage,120).
power(sandstorm,0).
power(giga_drain,75).
power(endure,0).
power(charm,0).
power(rollout,30).
power(false_swipe,40).
power(swagger,0).
power(milk_drink,0).
power(spark,65).
power(fury_cutter,20).
power(steel_wing,70).
power(mean_look,0).
power(attract,0).
power(sleep_talk,0).
power(heal_bell,0).
power(return,1).
power(present,1).
power(frustration,1).
power(safeguard,0).
power(pain_split,0).
power(sacred_fire,100).
power(magnitude,1).
power(dynamicpunch,100).
power(megahorn,120).
power(dragonbreath,60).
power(baton_pass,0).
power(encore,0).
power(pursuit,40).
power(rapid_spin,20).
power(sweet_scent,0).
power(iron_tail,100).
power(metal_claw,50).
power(vital_throw,70).
power(morning_sun,0).
power(synthesis,0).
power(moonlight,0).
power(hidden_power,1).
power(cross_chop,100).
power(twister,40).
power(rain_dance,0).
power(sunny_day,0).
power(crunch,80).
power(mirror_coat,1).
power(psych_up,0).
power(extremespeed,80).
power(ancientpower,60).
power(shadow_ball,80).
power(future_sight,100).
power(rock_smash,40).
power(whirlpool,35).
power(beat_up,1).
power(fake_out,40).
power(uproar,90).
power(stockpile,0).
power(spit_up,1).
power(swallow,0).
power(heat_wave,100).
power(hail,0).
power(torment,0).
power(flatter,0).
power(will_o_wisp,0).
power(memento,0).
power(facade,70).
power(focus_punch,150).
power(smellingsalt,60).
power(follow_me,0).
power(nature_power,0).
power(charge,0).
power(taunt,0).
power(helping_hand,0).
power(trick,0).
power(role_play,0).
power(wish,0).
power(assist,0).
power(ingrain,0).
power(superpower,120).
power(magic_coat,0).
power(recycle,0).
power(revenge,60).
power(brick_break,75).
power(yawn,0).
power(knock_off,20).
power(endeavor,1).
power(eruption,150).
power(skill_swap,0).
power(imprison,0).
power(refresh,0).
power(grudge,0).
power(snatch,0).
power(secret_power,70).
power(dive,80).
power(arm_thrust,15).
power(camouflage,0).
power(tail_glow,0).
power(luster_purge,70).
power(mist_ball,70).
power(featherdance,0).
power(teeter_dance,0).
power(blaze_kick,85).
power(mud_sport,0).
power(ice_ball,30).
power(needle_arm,60).
power(slack_off,0).
power(hyper_voice,90).
power(poison_fang,50).
power(crush_claw,75).
power(blast_burn,150).
power(hydro_cannon,150).
power(meteor_mash,100).
power(astonish,30).
power(weather_ball,50).
power(aromatherapy,0).
power(fake_tears,0).
power(air_cutter,55).
power(overheat,140).
power(odor_sleuth,0).
power(rock_tomb,50).
power(silver_wind,60).
power(metal_sound,0).
power(grasswhistle,0).
power(tickle,0).
power(cosmic_power,0).
power(water_spout,150).
power(signal_beam,75).
power(shadow_punch,60).
power(extrasensory,80).
power(sky_uppercut,85).
power(sand_tomb,35).
power(sheer_cold,1).
power(muddy_water,95).
power(bullet_seed,25).
power(aerial_ace,60).
power(icicle_spear,25).
power(iron_defense,0).
power(block,0).
power(howl,0).
power(dragon_claw,80).
power(frenzy_plant,150).
power(bulk_up,0).
power(bounce,85).
power(mud_shot,55).
power(poison_tail,50).
power(covet,60).
power(volt_tackle,120).
power(magical_leaf,60).
power(water_sport,0).
power(calm_mind,0).
power(leaf_blade,90).
power(dragon_dance,0).
power(rock_blast,25).
power(shock_wave,60).
power(water_pulse,60).
power(doom_desire,140).
power(psycho_boost,140).
power(roost,0).
power(gravity,0).
power(miracle_eye,0).
power(wake_up_slap,60).
power(hammer_arm,100).
power(gyro_ball,1).
power(healing_wish,0).
power(brine,65).
power(natural_gift,1).
power(feint,30).
power(pluck,60).
power(tailwind,0).
power(acupressure,0).
power(metal_burst,1).
power(u_turn,70).
power(close_combat,120).
power(payback,50).
power(assurance,50).
power(embargo,0).
power(fling,1).
power(psycho_shift,0).
power(trump_card,1).
power(heal_block,0).
power(wring_out,1).
power(power_trick,0).
power(gastro_acid,0).
power(lucky_chant,0).
power(me_first,1).
power(copycat,0).
power(power_swap,0).
power(guard_swap,0).
power(punishment,1).
power(last_resort,140).
power(worry_seed,0).
power(sucker_punch,80).
power(toxic_spikes,0).
power(heart_swap,0).
power(aqua_ring,0).
power(magnet_rise,0).
power(flare_blitz,120).
power(force_palm,60).
power(aura_sphere,90).
power(rock_polish,0).
power(poison_jab,80).
power(dark_pulse,80).
power(night_slash,70).
power(aqua_tail,90).
power(seed_bomb,80).
power(air_slash,75).
power(x_scissor,80).
power(bug_buzz,90).
power(dragon_pulse,90).
power(dragon_rush,100).
power(power_gem,70).
power(drain_punch,75).
power(vacuum_wave,40).
power(focus_blast,120).
power(energy_ball,80).
power(brave_bird,120).
power(earth_power,90).
power(switcheroo,0).
power(giga_impact,150).
power(nasty_plot,0).
power(bullet_punch,40).
power(avalanche,60).
power(ice_shard,40).
power(shadow_claw,70).
power(thunder_fang,65).
power(ice_fang,65).
power(fire_fang,65).
power(shadow_sneak,40).
power(mud_bomb,65).
power(psycho_cut,70).
power(zen_headbutt,80).
power(mirror_shot,65).
power(flash_cannon,80).
power(rock_climb,90).
power(defog,0).
power(trick_room,0).
power(draco_meteor,140).
power(discharge,80).
power(lava_plume,80).
power(leaf_storm,140).
power(power_whip,120).
power(rock_wrecker,150).
power(cross_poison,70).
power(gunk_shot,120).
power(iron_head,80).
power(magnet_bomb,60).
power(stone_edge,100).
power(captivate,0).
power(stealth_rock,0).
power(grass_knot,1).
power(chatter,60).
power(judgment,100).
power(bug_bite,60).
power(charge_beam,50).
power(wood_hammer,120).
power(aqua_jet,40).
power(attack_order,90).
power(defend_order,0).
power(heal_order,0).
power(head_smash,150).
power(double_hit,35).
power(roar_of_time,150).
power(spacial_rend,100).
power(lunar_dance,0).
power(crush_grip,1).
power(magma_storm,120).
power(dark_void,0).
power(seed_flare,120).
power(ominous_wind,60).
power(shadow_force,120).
power(hone_claws,0).
power(wide_guard,0).
power(guard_split,0).
power(power_split,0).
power(wonder_room,0).
power(psyshock,80).
power(venoshock,65).
power(autotomize,0).
power(rage_powder,0).
power(telekinesis,0).
power(magic_room,0).
power(smack_down,50).
power(storm_throw,40).
power(flame_burst,70).
power(sludge_wave,95).
power(quiver_dance,0).
power(heavy_slam,1).
power(synchronoise,70).
power(electro_ball,1).
power(soak,0).
power(flame_charge,50).
power(coil,0).
power(low_sweep,60).
power(acid_spray,40).
power(foul_play,95).
power(simple_beam,0).
power(entrainment,0).
power(after_you,0).
power(round,60).
power(echoed_voice,40).
power(chip_away,70).
power(clear_smog,50).
power(stored_power,20).
power(quick_guard,0).
power(ally_switch,0).
power(scald,80).
power(shell_smash,0).
power(heal_pulse,0).
power(hex,50).
power(sky_drop,60).
power(shift_gear,0).
power(circle_throw,60).
power(incinerate,30).
power(quash,0).
power(acrobatics,55).
power(reflect_type,0).
power(retaliate,70).
power(final_gambit,1).
power(bestow,0).
power(inferno,100).
power(water_pledge,50).
power(fire_pledge,50).
power(grass_pledge,50).
power(volt_switch,70).
power(struggle_bug,30).
power(bulldoze,60).
power(frost_breath,40).
power(dragon_tail,60).
power(work_up,0).
power(electroweb,55).
power(wild_charge,90).
power(drill_run,80).
power(dual_chop,40).
power(heart_stamp,60).
power(horn_leech,75).
power(sacred_sword,90).
power(razor_shell,75).
power(heat_crash,1).
power(leaf_tornado,65).
power(steamroller,65).
power(cotton_guard,0).
power(night_daze,85).
power(psystrike,100).
power(tail_slap,25).
power(hurricane,120).
power(head_charge,120).
power(gear_grind,50).
power(searing_shot,100).
power(techno_blast,85).
power(relic_song,75).
power(secret_sword,85).
power(glaciate,65).
power(bolt_strike,130).
power(blue_flare,130).
power(fiery_dance,80).
power(freeze_shock,140).
power(ice_burn,140).
power(snarl,55).
power(icicle_crash,85).
power(v_create,180).
power(fusion_flare,100).
power(fusion_bolt,100).
power(baby_doll_eyes,0).
power(belch,120).
power(boomburst,140).
power(confide,0).
power(crafty_shield,0).
power(dazzling_gleam,80).
power(disarming_voice,40).
power(draining_kiss,50).
power(eerie_impulse,0).
power(electric_terrain,0).
power(electrify,0).
power(fairy_lock,0).
power(fairy_wind,40).
power(fell_stinger,30).
power(flower_shield,0).
power(flying_press,80).
power(forests_curse,0).
power(freeze_dry,70).
power(geomancy,0).
power(grassy_terrain,0).
power(infestation,20).
power(ion_deluge,0).
power(kings_shield,0).
power(lands_wrath,90).
power(magnetic_flux,0).
power(mat_block,0).
power(misty_terrain,0).
power(moonblast,95).
power(mystical_fire,65).
power(noble_roar,0).
power(nuzzle,20).
power(oblivion_wing,80).
power(parabolic_charge,50).
power(parting_shot,0).
power(petal_blizzard,90).
power(phantom_force,90).
power(play_nice,0).
power(play_rough,90).
power(powder,0).
power(power_up_punch,40).
power(rototiller,0).
power(spiky_shield,0).
power(sticky_web,0).
power(topsy_turvy,0).
power(trick_or_treat,0).
power(venom_drench,0).
power(water_shuriken,15).
power(aromatic_mist,0).
power(shadow_rush,55).
power(shadow_blast,80).
power(shadow_blitz,40).
power(shadow_bolt,75).
power(shadow_break,75).
power(shadow_chill,75).
power(shadow_end,120).
power(shadow_fire,75).
power(shadow_rave,70).
power(shadow_storm,95).
power(shadow_wave,50).
power(shadow_down,0).
power(shadow_half,1).
power(shadow_hold,0).
power(shadow_mist,0).
power(shadow_panic,0).
power(shadow_shed,0).
power(shadow_sky,0).
power(pound,40).
power(karate_chop,50).
power(doubleslap,15).
power(comet_punch,18).
power(mega_punch,80).
power(pay_day,40).
power(fire_punch,75).
power(ice_punch,75).
power(thunderpunch,75).
power(scratch,40).
power(vicegrip,55).
power(guillotine,1).
power(razor_wind,80).
power(swords_dance,0).
power(cut,50).
power(gust,40).
power(wing_attack,60).
power(whirlwind,0).
power(fly,90).
power(bind,15).
power(slam,80).
power(vine_whip,35).
power(stomp,65).
power(double_kick,30).
power(mega_kick,120).
power(jump_kick,100).
power(rolling_kick,60).
power(sand_attack,0).
power(headbutt,70).
power(horn_attack,65).
power(fury_attack,15).
power(horn_drill,1).
power(tackle,50).
power(body_slam,85).
power(wrap,15).
power(take_down,90).
power(thrash,120).
power(double_edge,120).
power(tail_whip,0).
power(poison_sting,15).
power(twineedle,25).
power(pin_missile,14).
power(leer,0).
power(bite,60).
power(growl,0).
power(roar,0).
power(sing,0).
power(supersonic,0).
power(sonicboom,1).
power(disable,0).
power(acid,40).
power(ember,40).
power(flamethrower,95).
power(mist,0).
power(water_gun,40).
power(hydro_pump,120).
power(surf,95).
power(ice_beam,95).
power(blizzard,120).
power(psybeam,65).
power(bubblebeam,65).
power(aurora_beam,65).
power(hyper_beam,150).
power(peck,35).
power(drill_peck,80).
power(submission,80).
power(low_kick,1).
power(counter,1).
power(seismic_toss,1).
power(strength,80).
power(absorb,20).
power(mega_drain,40).
power(leech_seed,0).
power(growth,0).
power(razor_leaf,55).
power(solarbeam,120).
power(poisonpowder,0).
power(stun_spore,0).
power(sleep_powder,0).
power(petal_dance,120).
power(string_shot,0).
power(dragon_rage,1).
power(fire_spin,35).
power(thundershock,40).
power(thunderbolt,95).
power(thunder_wave,0).
power(thunder,120).
power(rock_throw,50).
power(earthquake,100).
power(fissure,1).
power(dig,80).
power(toxic,0).
power(confusion,50).
power(psychic,90).
power(hypnosis,0).
power(meditate,0).
power(agility,0).
power(quick_attack,40).
power(rage,20).
power(teleport,0).
power(night_shade,1).
power(mimic,0).
power(screech,0).
power(double_team,0).
power(recover,0).
power(harden,0).
power(minimize,0).
power(smokescreen,0).
power(confuse_ray,0).
power(withdraw,0).
power(defense_curl,0).
power(barrier,0).
power(light_screen,0).
power(haze,0).
power(reflect,0).
power(focus_energy,0).
power(bide,1).
power(metronome,0).
power(mirror_move,0).
power(selfdestruct,200).
power(egg_bomb,100).
power(lick,20).
power(smog,20).
power(sludge,65).
power(bone_club,65).
power(fire_blast,120).
power(waterfall,80).
power(clamp,35).
power(swift,60).
power(skull_bash,100).
power(spike_cannon,20).
power(constrict,10).
power(amnesia,0).
power(kinesis,0).
power(softboiled,0).
power(hi_jump_kick,130).
power(glare,0).
power(dream_eater,100).
power(poison_gas,0).
power(barrage,15).
power(leech_life,20).
power(lovely_kiss,0).
power(sky_attack,140).
power(transform,0).
power(bubble,20).
power(dizzy_punch,70).
power(spore,0).
power(flash,0).
power(psywave,1).
power(splash,0).
power(acid_armor,0).
power(crabhammer,90).
power(explosion,250).
power(fury_swipes,18).
power(bonemerang,50).
power(rest,0).
power(rock_slide,75).
power(hyper_fang,80).
power(sharpen,0).
power(conversion,0).
power(tri_attack,80).
power(super_fang,1).
power(slash,70).
power(substitute,0).
power(struggle,50).
power(sketch,0).
power(triple_kick,10).
power(thief,40).
power(spider_web,0).
power(mind_reader,0).
power(nightmare,0).
power(flame_wheel,60).
power(snore,40).
power(curse,0).
power(flail,1).
power(conversion_2,0).
power(aeroblast,100).
power(cotton_spore,0).
power(reversal,1).
power(spite,0).
power(powder_snow,40).
power(protect,0).
power(mach_punch,40).
power(scary_face,0).
power(faint_attack,60).
power(sweet_kiss,0).
power(belly_drum,0).
power(sludge_bomb,90).
power(mud_slap,20).
power(octazooka,65).
power(spikes,0).
power(zap_cannon,120).
power(foresight,0).
power(destiny_bond,0).
power(perish_song,0).
power(icy_wind,55).
power(detect,0).
power(bone_rush,25).
power(lock_on,0).
power(outrage,120).
power(sandstorm,0).
power(giga_drain,75).
power(endure,0).
power(charm,0).
power(rollout,30).
power(false_swipe,40).
power(swagger,0).
power(milk_drink,0).
power(spark,65).
power(fury_cutter,20).
power(steel_wing,70).
power(mean_look,0).
power(attract,0).
power(sleep_talk,0).
power(heal_bell,0).
power(return,1).
power(present,1).
power(frustration,1).
power(safeguard,0).
power(pain_split,0).
power(sacred_fire,100).
power(magnitude,1).
power(dynamicpunch,100).
power(megahorn,120).
power(dragonbreath,60).
power(baton_pass,0).
power(encore,0).
power(pursuit,40).
power(rapid_spin,20).
power(sweet_scent,0).
power(iron_tail,100).
power(metal_claw,50).
power(vital_throw,70).
power(morning_sun,0).
power(synthesis,0).
power(moonlight,0).
power(hidden_power,1).
power(cross_chop,100).
power(twister,40).
power(rain_dance,0).
power(sunny_day,0).
power(crunch,80).
power(mirror_coat,1).
power(psych_up,0).
power(extremespeed,80).
power(ancientpower,60).
power(shadow_ball,80).
power(future_sight,100).
power(rock_smash,40).
power(whirlpool,35).
power(beat_up,1).
power(fake_out,40).
power(uproar,90).
power(stockpile,0).
power(spit_up,1).
power(swallow,0).
power(heat_wave,100).
power(hail,0).
power(torment,0).
power(flatter,0).
power(will_o_wisp,0).
power(memento,0).
power(facade,70).
power(focus_punch,150).
power(smellingsalt,60).
power(follow_me,0).
power(nature_power,0).
power(charge,0).
power(taunt,0).
power(helping_hand,0).
power(trick,0).
power(role_play,0).
power(wish,0).
power(assist,0).
power(ingrain,0).
power(superpower,120).
power(magic_coat,0).
power(recycle,0).
power(revenge,60).
power(brick_break,75).
power(yawn,0).
power(knock_off,20).
power(endeavor,1).
power(eruption,150).
power(skill_swap,0).
power(imprison,0).
power(refresh,0).
power(grudge,0).
power(snatch,0).
power(secret_power,70).
power(dive,80).
power(arm_thrust,15).
power(camouflage,0).
power(tail_glow,0).
power(luster_purge,70).
power(mist_ball,70).
power(featherdance,0).
power(teeter_dance,0).
power(blaze_kick,85).
power(mud_sport,0).
power(ice_ball,30).
power(needle_arm,60).
power(slack_off,0).
power(hyper_voice,90).
power(poison_fang,50).
power(crush_claw,75).
power(blast_burn,150).
power(hydro_cannon,150).
power(meteor_mash,100).
power(astonish,30).
power(weather_ball,50).
power(aromatherapy,0).
power(fake_tears,0).
power(air_cutter,55).
power(overheat,140).
power(odor_sleuth,0).
power(rock_tomb,50).
power(silver_wind,60).
power(metal_sound,0).
power(grasswhistle,0).
power(tickle,0).
power(cosmic_power,0).
power(water_spout,150).
power(signal_beam,75).
power(shadow_punch,60).
power(extrasensory,80).
power(sky_uppercut,85).
power(sand_tomb,35).
power(sheer_cold,1).
power(muddy_water,95).
power(bullet_seed,25).
power(aerial_ace,60).
power(icicle_spear,25).
power(iron_defense,0).
power(block,0).
power(howl,0).
power(dragon_claw,80).
power(frenzy_plant,150).
power(bulk_up,0).
power(bounce,85).
power(mud_shot,55).
power(poison_tail,50).
power(covet,60).
power(volt_tackle,120).
power(magical_leaf,60).
power(water_sport,0).
power(calm_mind,0).
power(leaf_blade,90).
power(dragon_dance,0).
power(rock_blast,25).
power(shock_wave,60).
power(water_pulse,60).
power(doom_desire,140).
power(psycho_boost,140).
power(roost,0).
power(gravity,0).
power(miracle_eye,0).
power(wake_up_slap,60).
power(hammer_arm,100).
power(gyro_ball,1).
power(healing_wish,0).
power(brine,65).
power(natural_gift,1).
power(feint,30).
power(pluck,60).
power(tailwind,0).
power(acupressure,0).
power(metal_burst,1).
power(u_turn,70).
power(close_combat,120).
power(payback,50).
power(assurance,50).
power(embargo,0).
power(fling,1).
power(psycho_shift,0).
power(trump_card,1).
power(heal_block,0).
power(wring_out,1).
power(power_trick,0).
power(gastro_acid,0).
power(lucky_chant,0).
power(me_first,1).
power(copycat,0).
power(power_swap,0).
power(guard_swap,0).
power(punishment,1).
power(last_resort,140).
power(worry_seed,0).
power(sucker_punch,80).
power(toxic_spikes,0).
power(heart_swap,0).
power(aqua_ring,0).
power(magnet_rise,0).
power(flare_blitz,120).
power(force_palm,60).
power(aura_sphere,90).
power(rock_polish,0).
power(poison_jab,80).
power(dark_pulse,80).
power(night_slash,70).
power(aqua_tail,90).
power(seed_bomb,80).
power(air_slash,75).
power(x_scissor,80).
power(bug_buzz,90).
power(dragon_pulse,90).
power(dragon_rush,100).
power(power_gem,70).
power(drain_punch,75).
power(vacuum_wave,40).
power(focus_blast,120).
power(energy_ball,80).
power(brave_bird,120).
power(earth_power,90).
power(switcheroo,0).
power(giga_impact,150).
power(nasty_plot,0).
power(bullet_punch,40).
power(avalanche,60).
power(ice_shard,40).
power(shadow_claw,70).
power(thunder_fang,65).
power(ice_fang,65).
power(fire_fang,65).
power(shadow_sneak,40).
power(mud_bomb,65).
power(psycho_cut,70).
power(zen_headbutt,80).
power(mirror_shot,65).
power(flash_cannon,80).
power(rock_climb,90).
power(defog,0).
power(trick_room,0).
power(draco_meteor,140).
power(discharge,80).
power(lava_plume,80).
power(leaf_storm,140).
power(power_whip,120).
power(rock_wrecker,150).
power(cross_poison,70).
power(gunk_shot,120).
power(iron_head,80).
power(magnet_bomb,60).
power(stone_edge,100).
power(captivate,0).
power(stealth_rock,0).
power(grass_knot,1).
power(chatter,60).
power(judgment,100).
power(bug_bite,60).
power(charge_beam,50).
power(wood_hammer,120).
power(aqua_jet,40).
power(attack_order,90).
power(defend_order,0).
power(heal_order,0).
power(head_smash,150).
power(double_hit,35).
power(roar_of_time,150).
power(spacial_rend,100).
power(lunar_dance,0).
power(crush_grip,1).
power(magma_storm,120).
power(dark_void,0).
power(seed_flare,120).
power(ominous_wind,60).
power(shadow_force,120).
power(hone_claws,0).
power(wide_guard,0).
power(guard_split,0).
power(power_split,0).
power(wonder_room,0).
power(psyshock,80).
power(venoshock,65).
power(autotomize,0).
power(rage_powder,0).
power(telekinesis,0).
power(magic_room,0).
power(smack_down,50).
power(storm_throw,40).
power(flame_burst,70).
power(sludge_wave,95).
power(quiver_dance,0).
power(heavy_slam,1).
power(synchronoise,70).
power(electro_ball,1).
power(soak,0).
power(flame_charge,50).
power(coil,0).
power(low_sweep,60).
power(acid_spray,40).
power(foul_play,95).
power(simple_beam,0).
power(entrainment,0).
power(after_you,0).
power(round,60).
power(echoed_voice,40).
power(chip_away,70).
power(clear_smog,50).
power(stored_power,20).
power(quick_guard,0).
power(ally_switch,0).
power(scald,80).
power(shell_smash,0).
power(heal_pulse,0).
power(hex,50).
power(sky_drop,60).
power(shift_gear,0).
power(circle_throw,60).
power(incinerate,30).
power(quash,0).
power(acrobatics,55).
power(reflect_type,0).
power(retaliate,70).
power(final_gambit,1).
power(bestow,0).
power(inferno,100).
power(water_pledge,50).
power(fire_pledge,50).
power(grass_pledge,50).
power(volt_switch,70).
power(struggle_bug,30).
power(bulldoze,60).
power(frost_breath,40).
power(dragon_tail,60).
power(work_up,0).
power(electroweb,55).
power(wild_charge,90).
power(drill_run,80).
power(dual_chop,40).
power(heart_stamp,60).
power(horn_leech,75).
power(sacred_sword,90).
power(razor_shell,75).
power(heat_crash,1).
power(leaf_tornado,65).
power(steamroller,65).
power(cotton_guard,0).
power(night_daze,85).
power(psystrike,100).
power(tail_slap,25).
power(hurricane,120).
power(head_charge,120).
power(gear_grind,50).
power(searing_shot,100).
power(techno_blast,85).
power(relic_song,75).
power(secret_sword,85).
power(glaciate,65).
power(bolt_strike,130).
power(blue_flare,130).
power(fiery_dance,80).
power(freeze_shock,140).
power(ice_burn,140).
power(snarl,55).
power(icicle_crash,85).
power(v_create,180).
power(fusion_flare,100).
power(fusion_bolt,100).
power(baby_doll_eyes,0).
power(belch,120).
power(boomburst,140).
power(confide,0).
power(crafty_shield,0).
power(dazzling_gleam,80).
power(disarming_voice,40).
power(draining_kiss,50).
power(eerie_impulse,0).
power(electric_terrain,0).
power(electrify,0).
power(fairy_lock,0).
power(fairy_wind,40).
power(fell_stinger,30).
power(flower_shield,0).
power(flying_press,80).
power(forests_curse,0).
power(freeze_dry,70).
power(geomancy,0).
power(grassy_terrain,0).
power(infestation,20).
power(ion_deluge,0).
power(kings_shield,0).
power(lands_wrath,90).
power(magnetic_flux,0).
power(mat_block,0).
power(misty_terrain,0).
power(moonblast,95).
power(mystical_fire,65).
power(noble_roar,0).
power(nuzzle,20).
power(oblivion_wing,80).
power(parabolic_charge,50).
power(parting_shot,0).
power(petal_blizzard,90).
power(phantom_force,90).
power(play_nice,0).
power(play_rough,90).
power(powder,0).
power(power_up_punch,40).
power(rototiller,0).
power(spiky_shield,0).
power(sticky_web,0).
power(topsy_turvy,0).
power(trick_or_treat,0).
power(venom_drench,0).
power(water_shuriken,15).
power(aromatic_mist,0).
power(shadow_rush,55).
power(shadow_blast,80).
power(shadow_blitz,40).
power(shadow_bolt,75).
power(shadow_break,75).
power(shadow_chill,75).
power(shadow_end,120).
power(shadow_fire,75).
power(shadow_rave,70).
power(shadow_storm,95).
power(shadow_wave,50).
power(shadow_down,0).
power(shadow_half,1).
power(shadow_hold,0).
power(shadow_mist,0).
power(shadow_panic,0).
power(shadow_shed,0).
