:- module(powerfact,[]).
power(egg-bomb,100).
power(lick,20).
power(smog,20).
power(sludge,65).
power(bone-club,65).
power(fire-blast,120).
power(waterfall,80).
power(clamp,35).
power(swift,60).
power(skull-bash,100).
power(spike-cannon,20).
power(constrict,10).
power(amnesia,0).
power(kinesis,0).
power(softboiled,0).
power(hi-jump-kick,130).
power(glare,0).
power(dream-eater,100).
power(poison-gas,0).
power(barrage,15).
power(leech-life,20).
power(lovely-kiss,0).
power(sky-attack,140).
power(transform,0).
power(bubble,20).
power(dizzy-punch,70).
power(spore,0).
power(flash,0).
power(psywave,1).
power(splash,0).
power(acid-armor,0).
power(crabhammer,90).
power(explosion,250).
power(fury-swipes,18).
power(bonemerang,50).
power(rest,0).
power(rock-slide,75).
power(hyper-fang,80).
power(sharpen,0).
power(conversion,0).
power(tri-attack,80).
power(super-fang,1).
power(slash,70).
power(substitute,0).
power(struggle,50).
power(sketch,0).
power(triple-kick,10).
power(thief,40).
power(spider-web,0).
power(mind-reader,0).
power(nightmare,0).
power(flame-wheel,60).
power(snore,40).
power(curse,0).
power(flail,1).
power(conversion-2,0).
power(aeroblast,100).
power(cotton-spore,0).
power(reversal,1).
power(spite,0).
power(powder-snow,40).
power(protect,0).
power(mach-punch,40).
power(scary-face,0).
power(faint-attack,60).
power(sweet-kiss,0).
power(belly-drum,0).
power(sludge-bomb,90).
power(mud-slap,20).
power(octazooka,65).
power(spikes,0).
power(zap-cannon,120).
power(foresight,0).
power(destiny-bond,0).
power(perish-song,0).
power(icy-wind,55).
power(detect,0).
power(bone-rush,25).
power(lock-on,0).
power(outrage,120).
power(sandstorm,0).
power(giga-drain,75).
power(endure,0).
power(charm,0).
power(rollout,30).
power(false-swipe,40).
power(swagger,0).
power(milk-drink,0).
power(spark,65).
power(fury-cutter,20).
power(steel-wing,70).
power(mean-look,0).
power(attract,0).
power(sleep-talk,0).
power(heal-bell,0).
power(return,1).
power(present,1).
power(frustration,1).
power(safeguard,0).
power(pain-split,0).
power(sacred-fire,100).
power(magnitude,1).
power(dynamicpunch,100).
power(megahorn,120).
power(dragonbreath,60).
power(baton-pass,0).
power(encore,0).
power(pursuit,40).
power(rapid-spin,20).
power(sweet-scent,0).
power(iron-tail,100).
power(metal-claw,50).
power(vital-throw,70).
power(morning-sun,0).
power(synthesis,0).
power(moonlight,0).
power(hidden-power,1).
power(cross-chop,100).
power(twister,40).
power(rain-dance,0).
power(sunny-day,0).
power(crunch,80).
power(mirror-coat,1).
power(psych-up,0).
power(extremespeed,80).
power(ancientpower,60).
power(shadow-ball,80).
power(future-sight,100).
power(rock-smash,40).
power(whirlpool,35).
power(beat-up,1).
power(fake-out,40).
power(uproar,90).
power(stockpile,0).
power(spit-up,1).
power(swallow,0).
power(heat-wave,100).
power(hail,0).
power(torment,0).
power(flatter,0).
power(will-o-wisp,0).
power(memento,0).
power(facade,70).
power(focus-punch,150).
power(smellingsalt,60).
power(follow-me,0).
power(nature-power,0).
power(charge,0).
power(taunt,0).
power(helping-hand,0).
power(trick,0).
power(role-play,0).
power(wish,0).
power(assist,0).
power(ingrain,0).
power(superpower,120).
power(magic-coat,0).
power(recycle,0).
power(revenge,60).
power(brick-break,75).
power(yawn,0).
power(knock-off,20).
power(endeavor,1).
power(eruption,150).
power(skill-swap,0).
power(imprison,0).
power(refresh,0).
power(grudge,0).
power(snatch,0).
power(secret-power,70).
power(dive,80).
power(arm-thrust,15).
power(camouflage,0).
power(tail-glow,0).
power(luster-purge,70).
power(mist-ball,70).
power(featherdance,0).
power(teeter-dance,0).
power(blaze-kick,85).
power(mud-sport,0).
power(ice-ball,30).
power(needle-arm,60).
power(slack-off,0).
power(hyper-voice,90).
power(poison-fang,50).
power(crush-claw,75).
power(blast-burn,150).
power(hydro-cannon,150).
power(meteor-mash,100).
power(astonish,30).
power(weather-ball,50).
power(aromatherapy,0).
power(fake-tears,0).
power(air-cutter,55).
power(overheat,140).
power(odor-sleuth,0).
power(rock-tomb,50).
power(silver-wind,60).
power(metal-sound,0).
power(grasswhistle,0).
power(tickle,0).
power(cosmic-power,0).
power(water-spout,150).
power(signal-beam,75).
power(shadow-punch,60).
power(extrasensory,80).
power(sky-uppercut,85).
power(sand-tomb,35).
power(sheer-cold,1).
power(muddy-water,95).
power(bullet-seed,25).
power(aerial-ace,60).
power(icicle-spear,25).
power(iron-defense,0).
power(block,0).
power(howl,0).
power(dragon-claw,80).
power(frenzy-plant,150).
power(bulk-up,0).
power(bounce,85).
power(mud-shot,55).
power(poison-tail,50).
power(covet,60).
power(volt-tackle,120).
power(magical-leaf,60).
power(water-sport,0).
power(calm-mind,0).
power(leaf-blade,90).
power(dragon-dance,0).
power(rock-blast,25).
power(shock-wave,60).
power(water-pulse,60).
power(doom-desire,140).
power(psycho-boost,140).
power(roost,0).
power(gravity,0).
power(miracle-eye,0).
power(wake-up-slap,60).
power(hammer-arm,100).
power(gyro-ball,1).
power(healing-wish,0).
power(brine,65).
power(natural-gift,1).
power(feint,30).
power(pluck,60).
power(tailwind,0).
power(acupressure,0).
power(metal-burst,1).
power(u-turn,70).
power(close-combat,120).
power(payback,50).
power(assurance,50).
power(embargo,0).
power(fling,1).
power(psycho-shift,0).
power(trump-card,1).
power(heal-block,0).
power(wring-out,1).
power(power-trick,0).
power(gastro-acid,0).
power(lucky-chant,0).
power(me-first,1).
power(copycat,0).
power(power-swap,0).
power(guard-swap,0).
power(punishment,1).
power(last-resort,140).
power(worry-seed,0).
power(sucker-punch,80).
power(toxic-spikes,0).
power(heart-swap,0).
power(aqua-ring,0).
power(magnet-rise,0).
power(flare-blitz,120).
power(force-palm,60).
power(aura-sphere,90).
power(rock-polish,0).
power(poison-jab,80).
power(dark-pulse,80).
power(night-slash,70).
power(aqua-tail,90).
power(seed-bomb,80).
power(air-slash,75).
power(x-scissor,80).
power(bug-buzz,90).
power(dragon-pulse,90).
power(dragon-rush,100).
power(power-gem,70).
power(drain-punch,75).
power(vacuum-wave,40).
power(focus-blast,120).
power(energy-ball,80).
power(brave-bird,120).
power(earth-power,90).
power(switcheroo,0).
power(giga-impact,150).
power(nasty-plot,0).
power(bullet-punch,40).
power(avalanche,60).
power(ice-shard,40).
power(shadow-claw,70).
power(thunder-fang,65).
power(ice-fang,65).
power(fire-fang,65).
power(shadow-sneak,40).
power(mud-bomb,65).
power(psycho-cut,70).
power(zen-headbutt,80).
power(mirror-shot,65).
power(flash-cannon,80).
power(rock-climb,90).
power(defog,0).
power(trick-room,0).
power(draco-meteor,140).
power(discharge,80).
power(lava-plume,80).
power(leaf-storm,140).
power(power-whip,120).
power(rock-wrecker,150).
power(cross-poison,70).
power(gunk-shot,120).
power(iron-head,80).
power(magnet-bomb,60).
power(stone-edge,100).
power(captivate,0).
power(stealth-rock,0).
power(grass-knot,1).
power(chatter,60).
power(judgment,100).
power(bug-bite,60).
power(charge-beam,50).
power(wood-hammer,120).
power(aqua-jet,40).
power(attack-order,90).
power(defend-order,0).
power(heal-order,0).
power(head-smash,150).
power(double-hit,35).
power(roar-of-time,150).
power(spacial-rend,100).
power(lunar-dance,0).
power(crush-grip,1).
power(magma-storm,120).
power(dark-void,0).
power(seed-flare,120).
power(ominous-wind,60).
power(shadow-force,120).
power(hone-claws,0).
power(wide-guard,0).
power(guard-split,0).
power(power-split,0).
power(wonder-room,0).
power(psyshock,80).
power(venoshock,65).
power(autotomize,0).
power(rage-powder,0).
power(telekinesis,0).
power(magic-room,0).
power(smack-down,50).
power(storm-throw,40).
power(flame-burst,70).
power(sludge-wave,95).
power(quiver-dance,0).
power(heavy-slam,1).
power(synchronoise,70).
power(electro-ball,1).
power(soak,0).
power(flame-charge,50).
power(coil,0).
power(low-sweep,60).
power(acid-spray,40).
power(foul-play,95).
power(simple-beam,0).
power(entrainment,0).
power(after-you,0).
power(round,60).
power(echoed-voice,40).
power(chip-away,70).
power(clear-smog,50).
power(stored-power,20).
power(quick-guard,0).
power(ally-switch,0).
power(scald,80).
power(shell-smash,0).
power(heal-pulse,0).
power(hex,50).
power(sky-drop,60).
power(shift-gear,0).
power(circle-throw,60).
power(incinerate,30).
power(quash,0).
power(acrobatics,55).
power(reflect-type,0).
power(retaliate,70).
power(final-gambit,1).
power(bestow,0).
power(inferno,100).
power(water-pledge,50).
power(fire-pledge,50).
power(grass-pledge,50).
power(volt-switch,70).
power(struggle-bug,30).
power(bulldoze,60).
power(frost-breath,40).
power(dragon-tail,60).
power(work-up,0).
power(electroweb,55).
power(wild-charge,90).
power(drill-run,80).
power(dual-chop,40).
power(heart-stamp,60).
power(horn-leech,75).
power(sacred-sword,90).
power(razor-shell,75).
power(heat-crash,1).
power(leaf-tornado,65).
power(steamroller,65).
power(cotton-guard,0).
power(night-daze,85).
power(psystrike,100).
power(tail-slap,25).
power(hurricane,120).
power(head-charge,120).
power(gear-grind,50).
power(searing-shot,100).
power(techno-blast,85).
power(relic-song,75).
power(secret-sword,85).
power(glaciate,65).
power(bolt-strike,130).
power(blue-flare,130).
power(fiery-dance,80).
power(freeze-shock,140).
power(ice-burn,140).
power(snarl,55).
power(icicle-crash,85).
power(v-create,180).
power(fusion-flare,100).
power(fusion-bolt,100).
power(baby-doll-eyes,0).
power(belch,120).
power(boomburst,140).
power(confide,0).
power(crafty-shield,0).
power(dazzling-gleam,80).
power(disarming-voice,40).
power(draining-kiss,50).
power(eerie-impulse,0).
power(electric-terrain,0).
power(electrify,0).
power(fairy-lock,0).
power(fairy-wind,40).
power(fell-stinger,30).
power(flower-shield,0).
power(flying-press,80).
power(forests-curse,0).
power(freeze-dry,70).
power(geomancy,0).
power(grassy-terrain,0).
power(infestation,20).
power(ion-deluge,0).
power(kings-shield,0).
power(lands-wrath,90).
power(magnetic-flux,0).
power(mat-block,0).
power(misty-terrain,0).
power(moonblast,95).
power(mystical-fire,65).
power(noble-roar,0).
power(nuzzle,20).
power(oblivion-wing,80).
power(parabolic-charge,50).
power(parting-shot,0).
power(petal-blizzard,90).
power(phantom-force,90).
power(play-nice,0).
power(play-rough,90).
power(powder,0).
power(power-up-punch,40).
power(rototiller,0).
power(spiky-shield,0).
power(sticky-web,0).
power(topsy-turvy,0).
power(trick-or-treat,0).
power(venom-drench,0).
power(water-shuriken,15).
power(aromatic-mist,0).
power(shadow-rush,55).
power(shadow-blast,80).
power(shadow-blitz,40).
power(shadow-bolt,75).
power(shadow-break,75).
power(shadow-chill,75).
power(shadow-end,120).
power(shadow-fire,75).
power(shadow-rave,70).
power(shadow-storm,95).
power(shadow-wave,50).
power(shadow-down,0).
power(shadow-half,1).
power(shadow-hold,0).
power(shadow-mist,0).
power(shadow-panic,0).
power(shadow-shed,0).
power(shadow-sky,0).
power(pound,40).
power(karate-chop,50).
power(doubleslap,15).
power(comet-punch,18).
power(mega-punch,80).
power(pay-day,40).
power(fire-punch,75).
power(ice-punch,75).
power(thunderpunch,75).
power(scratch,40).
power(vicegrip,55).
power(guillotine,1).
power(razor-wind,80).
power(swords-dance,0).
power(cut,50).
power(gust,40).
power(wing-attack,60).
power(whirlwind,0).
power(fly,90).
power(bind,15).
power(slam,80).
power(vine-whip,35).
power(stomp,65).
power(double-kick,30).
power(mega-kick,120).
power(jump-kick,100).
power(rolling-kick,60).
power(sand-attack,0).
power(headbutt,70).
power(horn-attack,65).
power(fury-attack,15).
power(horn-drill,1).
power(tackle,50).
power(body-slam,85).
power(wrap,15).
power(take-down,90).
power(thrash,120).
power(double-edge,120).
power(tail-whip,0).
power(poison-sting,15).
power(twineedle,25).
power(pin-missile,14).
power(leer,0).
power(bite,60).
power(growl,0).
power(roar,0).
power(sing,0).
power(supersonic,0).
power(sonicboom,1).
power(disable,0).
power(acid,40).
power(ember,40).
power(flamethrower,95).
power(mist,0).
power(water-gun,40).
power(hydro-pump,120).
power(surf,95).
power(ice-beam,95).
power(blizzard,120).
power(psybeam,65).
power(bubblebeam,65).
power(aurora-beam,65).
power(hyper-beam,150).
power(peck,35).
power(drill-peck,80).
power(submission,80).
power(low-kick,1).
power(counter,1).
power(seismic-toss,1).
power(strength,80).
power(absorb,20).
power(mega-drain,40).
power(leech-seed,0).
power(growth,0).
power(razor-leaf,55).
power(solarbeam,120).
power(poisonpowder,0).
power(stun-spore,0).
power(sleep-powder,0).
power(petal-dance,120).
power(string-shot,0).
power(dragon-rage,1).
power(fire-spin,35).
power(thundershock,40).
power(thunderbolt,95).
power(thunder-wave,0).
power(thunder,120).
power(rock-throw,50).
power(earthquake,100).
power(fissure,1).
power(dig,80).
power(toxic,0).
power(confusion,50).
power(psychic,90).
power(hypnosis,0).
power(meditate,0).
power(agility,0).
power(quick-attack,40).
power(rage,20).
power(teleport,0).
power(night-shade,1).
power(mimic,0).
power(screech,0).
power(double-team,0).
power(recover,0).
power(harden,0).
power(minimize,0).
power(smokescreen,0).
power(confuse-ray,0).
power(withdraw,0).
power(defense-curl,0).
power(barrier,0).
power(light-screen,0).
power(haze,0).
power(reflect,0).
power(focus-energy,0).
power(bide,1).
power(metronome,0).
power(mirror-move,0).
power(selfdestruct,200).
power(egg-bomb,100).
power(lick,20).
power(smog,20).
power(sludge,65).
power(bone-club,65).
power(fire-blast,120).
power(waterfall,80).
power(clamp,35).
power(swift,60).
power(skull-bash,100).
power(spike-cannon,20).
power(constrict,10).
power(amnesia,0).
power(kinesis,0).
power(softboiled,0).
power(hi-jump-kick,130).
power(glare,0).
power(dream-eater,100).
power(poison-gas,0).
power(barrage,15).
power(leech-life,20).
power(lovely-kiss,0).
power(sky-attack,140).
power(transform,0).
power(bubble,20).
power(dizzy-punch,70).
power(spore,0).
power(flash,0).
power(psywave,1).
power(splash,0).
power(acid-armor,0).
power(crabhammer,90).
power(explosion,250).
power(fury-swipes,18).
power(bonemerang,50).
power(rest,0).
power(rock-slide,75).
power(hyper-fang,80).
power(sharpen,0).
power(conversion,0).
power(tri-attack,80).
power(super-fang,1).
power(slash,70).
power(substitute,0).
power(struggle,50).
power(sketch,0).
power(triple-kick,10).
power(thief,40).
power(spider-web,0).
power(mind-reader,0).
power(nightmare,0).
power(flame-wheel,60).
power(snore,40).
power(curse,0).
power(flail,1).
power(conversion-2,0).
power(aeroblast,100).
power(cotton-spore,0).
power(reversal,1).
power(spite,0).
power(powder-snow,40).
power(protect,0).
power(mach-punch,40).
power(scary-face,0).
power(faint-attack,60).
power(sweet-kiss,0).
power(belly-drum,0).
power(sludge-bomb,90).
power(mud-slap,20).
power(octazooka,65).
power(spikes,0).
power(zap-cannon,120).
power(foresight,0).
power(destiny-bond,0).
power(perish-song,0).
power(icy-wind,55).
power(detect,0).
power(bone-rush,25).
power(lock-on,0).
power(outrage,120).
power(sandstorm,0).
power(giga-drain,75).
power(endure,0).
power(charm,0).
power(rollout,30).
power(false-swipe,40).
power(swagger,0).
power(milk-drink,0).
power(spark,65).
power(fury-cutter,20).
power(steel-wing,70).
power(mean-look,0).
power(attract,0).
power(sleep-talk,0).
power(heal-bell,0).
power(return,1).
power(present,1).
power(frustration,1).
power(safeguard,0).
power(pain-split,0).
power(sacred-fire,100).
power(magnitude,1).
power(dynamicpunch,100).
power(megahorn,120).
power(dragonbreath,60).
power(baton-pass,0).
power(encore,0).
power(pursuit,40).
power(rapid-spin,20).
power(sweet-scent,0).
power(iron-tail,100).
power(metal-claw,50).
power(vital-throw,70).
power(morning-sun,0).
power(synthesis,0).
power(moonlight,0).
power(hidden-power,1).
power(cross-chop,100).
power(twister,40).
power(rain-dance,0).
power(sunny-day,0).
power(crunch,80).
power(mirror-coat,1).
power(psych-up,0).
power(extremespeed,80).
power(ancientpower,60).
power(shadow-ball,80).
power(future-sight,100).
power(rock-smash,40).
power(whirlpool,35).
power(beat-up,1).
power(fake-out,40).
power(uproar,90).
power(stockpile,0).
power(spit-up,1).
power(swallow,0).
power(heat-wave,100).
power(hail,0).
power(torment,0).
power(flatter,0).
power(will-o-wisp,0).
power(memento,0).
power(facade,70).
power(focus-punch,150).
power(smellingsalt,60).
power(follow-me,0).
power(nature-power,0).
power(charge,0).
power(taunt,0).
power(helping-hand,0).
power(trick,0).
power(role-play,0).
power(wish,0).
power(assist,0).
power(ingrain,0).
power(superpower,120).
power(magic-coat,0).
power(recycle,0).
power(revenge,60).
power(brick-break,75).
power(yawn,0).
power(knock-off,20).
power(endeavor,1).
power(eruption,150).
power(skill-swap,0).
power(imprison,0).
power(refresh,0).
power(grudge,0).
power(snatch,0).
power(secret-power,70).
power(dive,80).
power(arm-thrust,15).
power(camouflage,0).
power(tail-glow,0).
power(luster-purge,70).
power(mist-ball,70).
power(featherdance,0).
power(teeter-dance,0).
power(blaze-kick,85).
power(mud-sport,0).
power(ice-ball,30).
power(needle-arm,60).
power(slack-off,0).
power(hyper-voice,90).
power(poison-fang,50).
power(crush-claw,75).
power(blast-burn,150).
power(hydro-cannon,150).
power(meteor-mash,100).
power(astonish,30).
power(weather-ball,50).
power(aromatherapy,0).
power(fake-tears,0).
power(air-cutter,55).
power(overheat,140).
power(odor-sleuth,0).
power(rock-tomb,50).
power(silver-wind,60).
power(metal-sound,0).
power(grasswhistle,0).
power(tickle,0).
power(cosmic-power,0).
power(water-spout,150).
power(signal-beam,75).
power(shadow-punch,60).
power(extrasensory,80).
power(sky-uppercut,85).
power(sand-tomb,35).
power(sheer-cold,1).
power(muddy-water,95).
power(bullet-seed,25).
power(aerial-ace,60).
power(icicle-spear,25).
power(iron-defense,0).
power(block,0).
power(howl,0).
power(dragon-claw,80).
power(frenzy-plant,150).
power(bulk-up,0).
power(bounce,85).
power(mud-shot,55).
power(poison-tail,50).
power(covet,60).
power(volt-tackle,120).
power(magical-leaf,60).
power(water-sport,0).
power(calm-mind,0).
power(leaf-blade,90).
power(dragon-dance,0).
power(rock-blast,25).
power(shock-wave,60).
power(water-pulse,60).
power(doom-desire,140).
power(psycho-boost,140).
power(roost,0).
power(gravity,0).
power(miracle-eye,0).
power(wake-up-slap,60).
power(hammer-arm,100).
power(gyro-ball,1).
power(healing-wish,0).
power(brine,65).
power(natural-gift,1).
power(feint,30).
power(pluck,60).
power(tailwind,0).
power(acupressure,0).
power(metal-burst,1).
power(u-turn,70).
power(close-combat,120).
power(payback,50).
power(assurance,50).
power(embargo,0).
power(fling,1).
power(psycho-shift,0).
power(trump-card,1).
power(heal-block,0).
power(wring-out,1).
power(power-trick,0).
power(gastro-acid,0).
power(lucky-chant,0).
power(me-first,1).
power(copycat,0).
power(power-swap,0).
power(guard-swap,0).
power(punishment,1).
power(last-resort,140).
power(worry-seed,0).
power(sucker-punch,80).
power(toxic-spikes,0).
power(heart-swap,0).
power(aqua-ring,0).
power(magnet-rise,0).
power(flare-blitz,120).
power(force-palm,60).
power(aura-sphere,90).
power(rock-polish,0).
power(poison-jab,80).
power(dark-pulse,80).
power(night-slash,70).
power(aqua-tail,90).
power(seed-bomb,80).
power(air-slash,75).
power(x-scissor,80).
power(bug-buzz,90).
power(dragon-pulse,90).
power(dragon-rush,100).
power(power-gem,70).
power(drain-punch,75).
power(vacuum-wave,40).
power(focus-blast,120).
power(energy-ball,80).
power(brave-bird,120).
power(earth-power,90).
power(switcheroo,0).
power(giga-impact,150).
power(nasty-plot,0).
power(bullet-punch,40).
power(avalanche,60).
power(ice-shard,40).
power(shadow-claw,70).
power(thunder-fang,65).
power(ice-fang,65).
power(fire-fang,65).
power(shadow-sneak,40).
power(mud-bomb,65).
power(psycho-cut,70).
power(zen-headbutt,80).
power(mirror-shot,65).
power(flash-cannon,80).
power(rock-climb,90).
power(defog,0).
power(trick-room,0).
power(draco-meteor,140).
power(discharge,80).
power(lava-plume,80).
power(leaf-storm,140).
power(power-whip,120).
power(rock-wrecker,150).
power(cross-poison,70).
power(gunk-shot,120).
power(iron-head,80).
power(magnet-bomb,60).
power(stone-edge,100).
power(captivate,0).
power(stealth-rock,0).
power(grass-knot,1).
power(chatter,60).
power(judgment,100).
power(bug-bite,60).
power(charge-beam,50).
power(wood-hammer,120).
power(aqua-jet,40).
power(attack-order,90).
power(defend-order,0).
power(heal-order,0).
power(head-smash,150).
power(double-hit,35).
power(roar-of-time,150).
power(spacial-rend,100).
power(lunar-dance,0).
power(crush-grip,1).
power(magma-storm,120).
power(dark-void,0).
power(seed-flare,120).
power(ominous-wind,60).
power(shadow-force,120).
power(hone-claws,0).
power(wide-guard,0).
power(guard-split,0).
power(power-split,0).
power(wonder-room,0).
power(psyshock,80).
power(venoshock,65).
power(autotomize,0).
power(rage-powder,0).
power(telekinesis,0).
power(magic-room,0).
power(smack-down,50).
power(storm-throw,40).
power(flame-burst,70).
power(sludge-wave,95).
power(quiver-dance,0).
power(heavy-slam,1).
power(synchronoise,70).
power(electro-ball,1).
power(soak,0).
power(flame-charge,50).
power(coil,0).
power(low-sweep,60).
power(acid-spray,40).
power(foul-play,95).
power(simple-beam,0).
power(entrainment,0).
power(after-you,0).
power(round,60).
power(echoed-voice,40).
power(chip-away,70).
power(clear-smog,50).
power(stored-power,20).
power(quick-guard,0).
power(ally-switch,0).
power(scald,80).
power(shell-smash,0).
power(heal-pulse,0).
power(hex,50).
power(sky-drop,60).
power(shift-gear,0).
power(circle-throw,60).
power(incinerate,30).
power(quash,0).
power(acrobatics,55).
power(reflect-type,0).
power(retaliate,70).
power(final-gambit,1).
power(bestow,0).
power(inferno,100).
power(water-pledge,50).
power(fire-pledge,50).
power(grass-pledge,50).
power(volt-switch,70).
power(struggle-bug,30).
power(bulldoze,60).
power(frost-breath,40).
power(dragon-tail,60).
power(work-up,0).
power(electroweb,55).
power(wild-charge,90).
power(drill-run,80).
power(dual-chop,40).
power(heart-stamp,60).
power(horn-leech,75).
power(sacred-sword,90).
power(razor-shell,75).
power(heat-crash,1).
power(leaf-tornado,65).
power(steamroller,65).
power(cotton-guard,0).
power(night-daze,85).
power(psystrike,100).
power(tail-slap,25).
power(hurricane,120).
power(head-charge,120).
power(gear-grind,50).
power(searing-shot,100).
power(techno-blast,85).
power(relic-song,75).
power(secret-sword,85).
power(glaciate,65).
power(bolt-strike,130).
power(blue-flare,130).
power(fiery-dance,80).
power(freeze-shock,140).
power(ice-burn,140).
power(snarl,55).
power(icicle-crash,85).
power(v-create,180).
power(fusion-flare,100).
power(fusion-bolt,100).
power(baby-doll-eyes,0).
power(belch,120).
power(boomburst,140).
power(confide,0).
power(crafty-shield,0).
power(dazzling-gleam,80).
power(disarming-voice,40).
power(draining-kiss,50).
power(eerie-impulse,0).
power(electric-terrain,0).
power(electrify,0).
power(fairy-lock,0).
power(fairy-wind,40).
power(fell-stinger,30).
power(flower-shield,0).
power(flying-press,80).
power(forests-curse,0).
power(freeze-dry,70).
power(geomancy,0).
power(grassy-terrain,0).
power(infestation,20).
power(ion-deluge,0).
power(kings-shield,0).
power(lands-wrath,90).
power(magnetic-flux,0).
power(mat-block,0).
power(misty-terrain,0).
power(moonblast,95).
power(mystical-fire,65).
power(noble-roar,0).
power(nuzzle,20).
power(oblivion-wing,80).
power(parabolic-charge,50).
power(parting-shot,0).
power(petal-blizzard,90).
power(phantom-force,90).
power(play-nice,0).
power(play-rough,90).
power(powder,0).
power(power-up-punch,40).
power(rototiller,0).
power(spiky-shield,0).
power(sticky-web,0).
power(topsy-turvy,0).
power(trick-or-treat,0).
power(venom-drench,0).
power(water-shuriken,15).
power(aromatic-mist,0).
power(shadow-rush,55).
power(shadow-blast,80).
power(shadow-blitz,40).
power(shadow-bolt,75).
power(shadow-break,75).
power(shadow-chill,75).
power(shadow-end,120).
power(shadow-fire,75).
power(shadow-rave,70).
power(shadow-storm,95).
power(shadow-wave,50).
power(shadow-down,0).
power(shadow-half,1).
power(shadow-hold,0).
power(shadow-mist,0).
power(shadow-panic,0).
power(shadow-shed,0).
