:- module(typefact,[]).
type(normal).
type(fighting).
type(flying).
type(poison).
type(ground).
type(rock).
type(bug).
type(ghost).
type(steel).
type(fire).
type(water).
type(grass).
type(electric).
type(psychic).
type(ice).
type(dragon).
type(dark).
type(fairy).
effective(normal,rock,0.5).
effective(normal,steel,0.5).
effective(normal,ghost,0).
effective(normal,normal,1).
effective(normal,fighting,1).
effective(normal,flying,1).
effective(normal,poison,1).
effective(normal,ground,1).
effective(normal,bug,1).
effective(normal,fire,1).
effective(normal,water,1).
effective(normal,grass,1).
effective(normal,electric,1).
effective(normal,psychic,1).
effective(normal,ice,1).
effective(normal,dragon,1).
effective(normal,dark,1).
effective(normal,fairy,1).
effective(fighting,poison,0.5).
effective(fighting,flying,0.5).
effective(fighting,psychic,0.5).
effective(fighting,bug,0.5).
effective(fighting,fairy,0.5).
effective(fighting,normal,2).
effective(fighting,ice,2).
effective(fighting,rock,2).
effective(fighting,dark,2).
effective(fighting,steel,2).
effective(fighting,ghost,0).
effective(fighting,fighting,1).
effective(fighting,ground,1).
effective(fighting,fire,1).
effective(fighting,water,1).
effective(fighting,grass,1).
effective(fighting,electric,1).
effective(fighting,dragon,1).
effective(flying,electric,0.5).
effective(flying,rock,0.5).
effective(flying,steel,0.5).
effective(flying,grass,2).
effective(flying,fighting,2).
effective(flying,bug,2).
effective(flying,normal,1).
effective(flying,flying,1).
effective(flying,poison,1).
effective(flying,ground,1).
effective(flying,ghost,1).
effective(flying,fire,1).
effective(flying,water,1).
effective(flying,psychic,1).
effective(flying,ice,1).
effective(flying,dragon,1).
effective(flying,dark,1).
effective(flying,fairy,1).
effective(poison,poison,0.5).
effective(poison,ground,0.5).
effective(poison,rock,0.5).
effective(poison,ghost,0.5).
effective(poison,grass,2).
effective(poison,fairy,2).
effective(poison,steel,0).
effective(poison,normal,1).
effective(poison,fighting,1).
effective(poison,flying,1).
effective(poison,bug,1).
effective(poison,fire,1).
effective(poison,water,1).
effective(poison,electric,1).
effective(poison,psychic,1).
effective(poison,ice,1).
effective(poison,dragon,1).
effective(poison,dark,1).
effective(ground,ground,0.5).
effective(ground,bug,0.5).
effective(ground,fire,2).
effective(ground,electric,2).
effective(ground,poison,2).
effective(ground,rock,2).
effective(ground,steel,2).
effective(ground,flying,0).
effective(ground,normal,1).
effective(ground,fighting,1).
effective(ground,ghost,1).
effective(ground,water,1).
effective(ground,grass,0.5).
effective(ground,psychic,1).
effective(ground,ice,1).
effective(ground,dragon,1).
effective(ground,dark,1).
effective(ground,fairy,1).
effective(rock,fighting,0.5).
effective(rock,ground,0.5).
effective(rock,steel,0.5).
effective(rock,fire,2).
effective(rock,ice,2).
effective(rock,flying,2).
effective(rock,bug,2).
effective(rock,normal,1).
effective(rock,poison,1).
effective(rock,rock,1).
effective(rock,ghost,1).
effective(rock,water,1).
effective(rock,grass,1).
effective(rock,electric,1).
effective(rock,psychic,1).
effective(rock,dragon,1).
effective(rock,dark,1).
effective(rock,fairy,1).
effective(bug,fighting,0.5).
effective(bug,poison,0.5).
effective(bug,flying,0.5).
effective(bug,ghost,0.5).
effective(bug,steel,0.5).
effective(bug,fairy,0.5).
effective(bug,grass,2).
effective(bug,psychic,2).
effective(bug,dark,2).
effective(bug,normal,1).
effective(bug,ground,1).
effective(bug,rock,1).
effective(bug,bug,1).
effective(bug,fire,1).
effective(bug,water,1).
effective(bug,electric,1).
effective(bug,ice,1).
effective(bug,dragon,1).
effective(ghost,dark,0.5).
effective(ghost,psychic,2).
effective(ghost,ghost,2).
effective(ghost,normal,0).
effective(ghost,fighting,1).
effective(ghost,flying,1).
effective(ghost,poison,1).
effective(ghost,ground,1).
effective(ghost,rock,1).
effective(ghost,bug,1).
effective(ghost,steel,1).
effective(ghost,fire,1).
effective(ghost,water,1).
effective(ghost,grass,1).
effective(ghost,electric,1).
effective(ghost,ice,1).
effective(ghost,dragon,1).
effective(ghost,fairy,1).
effective(steel,fire,0.5).
effective(steel,water,0.5).
effective(steel,electric,0.5).
effective(steel,steel,0.5).
effective(steel,ice,2).
effective(steel,rock,2).
effective(steel,fairy,2).
effective(steel,normal,1).
effective(steel,fighting,1).
effective(steel,flying,1).
effective(steel,poison,1).
effective(steel,ground,1).
effective(steel,bug,1).
effective(steel,ghost,1).
effective(steel,grass,1).
effective(steel,psychic,1).
effective(steel,dragon,1).
effective(steel,dark,1).
effective(fire,fire,0.5).
effective(fire,water,0.5).
effective(fire,rock,0.5).
effective(fire,dragon,0.5).
effective(fire,grass,2).
effective(fire,ice,2).
effective(fire,bug,2).
effective(fire,steel,2).
effective(fire,normal,1).
effective(fire,fighting,1).
effective(fire,flying,1).
effective(fire,poison,1).
effective(fire,ground,1).
effective(fire,ghost,1).
effective(fire,electric,1).
effective(fire,psychic,1).
effective(fire,dark,1).
effective(fire,fairy,1).
effective(water,water,0.5).
effective(water,grass,0.5).
effective(water,dragon,0.5).
effective(water,fire,2).
effective(water,ground,2).
effective(water,rock,2).
effective(water,normal,1).
effective(water,fighting,1).
effective(water,flying,1).
effective(water,poison,1).
effective(water,bug,1).
effective(water,ghost,1).
effective(water,steel,1).
effective(water,electric,1).
effective(water,psychic,1).
effective(water,ice,1).
effective(water,dark,1).
effective(water,fairy,1).
effective(grass,fighting,0.5).
effective(grass,grass,0.5).
effective(grass,poison,0.5).
effective(grass,flying,0.5).
effective(grass,bug,0.5).
effective(grass,dragon,0.5).
effective(grass,steel,0.5).
effective(grass,water,2).
effective(grass,ground,2).
effective(grass,rock,2).
effective(grass,normal,1).
effective(grass,ghost,1).
effective(grass,fire,1).
effective(grass,electric,1).
effective(grass,psychic,1).
effective(grass,ice,1).
effective(grass,dark,1).
effective(grass,fairy,1).
effective(electric,electric,0.5).
effective(electric,grass,0.5).
effective(electric,dragon,0.5).
effective(electric,water,2).
effective(electric,flying,2).
effective(electric,ground,0).
effective(electric,normal,1).
effective(electric,fighting,1).
effective(electric,poison,1).
effective(electric,rock,1).
effective(electric,bug,1).
effective(electric,ghost,1).
effective(electric,steel,1).
effective(electric,fire,1).
effective(electric,psychic,1).
effective(electric,ice,1).
effective(electric,dark,1).
effective(electric,fairy,1).
effective(psychic,psychic,0.5).
effective(psychic,steel,0.5).
effective(psychic,fighting,2).
effective(psychic,poison,2).
effective(psychic,dark,0).
effective(psychic,normal,1).
effective(psychic,flying,1).
effective(psychic,ground,1).
effective(psychic,rock,1).
effective(psychic,bug,1).
effective(psychic,ghost,1).
effective(psychic,fire,1).
effective(psychic,water,1).
effective(psychic,grass,1).
effective(psychic,electric,1).
effective(psychic,ice,1).
effective(psychic,dragon,1).
effective(psychic,fairy,1).
effective(ice,fire,0.5).
effective(ice,water,0.5).
effective(ice,ice,0.5).
effective(ice,steel,0.5).
effective(ice,grass,2).
effective(ice,ground,2).
effective(ice,flying,2).
effective(ice,dragon,2).
effective(ice,normal,1).
effective(ice,fighting,1).
effective(ice,poison,1).
effective(ice,rock,1).
effective(ice,bug,1).
effective(ice,ghost,1).
effective(ice,electric,1).
effective(ice,psychic,1).
effective(ice,dark,1).
effective(ice,fairy,1).
effective(dragon,steel,0.5).
effective(dragon,dragon,2).
effective(dragon,psychic,1).
effective(dragon,fairy,0).
effective(dragon,normal,1).
effective(dragon,fighting,1).
effective(dragon,flying,1).
effective(dragon,poison,1).
effective(dragon,ground,1).
effective(dragon,rock,1).
effective(dragon,bug,1).
effective(dragon,ghost,1).
effective(dragon,fire,1).
effective(dragon,water,1).
effective(dragon,grass,1).
effective(dragon,electric,1).
effective(dragon,ice,1).
effective(dragon,dark,1).
effective(dark,fighting,0.5).
effective(dark,dark,0.5).
effective(dark,fairy,0.5).
effective(dark,ghost,2).
effective(dark,normal,1).
effective(dark,flying,1).
effective(dark,poison,1).
effective(dark,ground,1).
effective(dark,rock,1).
effective(dark,bug,1).
effective(dark,steel,1).
effective(dark,fire,1).
effective(dark,water,1).
effective(dark,grass,1).
effective(dark,electric,1).
effective(dark,psychic,1).
effective(dark,ice,1).
effective(dark,dragon,1).
effective(fairy,fire,0.5).
effective(fairy,poison,0.5).
effective(fairy,steel,0.5).
effective(fairy,fighting,2).
effective(fairy,dragon,2).
effective(fairy,dark,2).
effective(fairy,normal,1).
effective(fairy,flying,1).
effective(fairy,ground,1).
effective(fairy,rock,1).
effective(fairy,bug,1).
effective(fairy,ghost,1).
effective(fairy,water,1).
effective(fairy,grass,1).
effective(fairy,electric,1).
effective(fairy,psychic,1).
effective(fairy,ice,1).
effective(fairy,fairy,1).
